### ISSUE TITLE
Main Menu design concept

### ISSUE THREAD

**Issue by Ravennholm** [momentum-mod/game#10]
My concept: http://imgur.com/a/GT4vZ  ( Name can be changed easy but we just need a name now )

**Comment by Flipybitz** [comment]
I'll put my contribution here for further reference as well. *(Mine is missing a few things, but they shouldn't be too hard to just throw in)*
Start up: http://i.imgur.com/Sci3O85.png
Map list: http://i.imgur.com/boKCYsZ.png
Map selected: http://i.imgur.com/atia7gp.png

#### About fonts
--------------
Something to keep in mind for anyone else wanting to contribute, some fonts won't allow us to commercially distribute something that has their font in it, so either go to dafont and advance search for free/public domain fonts, or if you're in doubt if the font you used is allowed, you should probably play it safe... The font I used for my menu (Gravity) is listed under Public domain/GPL/OFL, so mine _should_ be alright.

**Comment by GeordieP** [comment]
I think at this point, I like the one by @Ravennholm better, just because everything is on one screen. @Flipybitz yours is more aesthetically pleasing, but I can't help but think that using the menu would suck. If you wanted to view the preview image of a map, you'd have to click it and be brought to an entirely different screen (which at this point doesn't have a back button, I might add). That would probably get tedious. Nice thing about the other one is that you don't lose your view of the list whenever you click a map.

Also, for everyone, I'm not sure exactly how flexible UI creation in the source engine is, but keep in mind that things like glowing text might not be possible without images, which is obviously not a viable option for something like a list of maps.

**Comment by Gocnak** [comment]
Relevent: https://developer.valvesoftware.com/wiki/Custom_Menu_Screen and https://developer.valvesoftware.com/wiki/Category:VGUI

**Comment by RabsRincon** [comment]
New gameui implemented.
