### ISSUE TITLE
Map state does not reset with timer reset

### ISSUE THREAD

**Issue by lodyb** [momentum-mod/game#102]
A problem that has come to light while working on my map is that the map entities do not reset on a timer reset.

Examples:
- Opening locked doors will stay open on timer reset
- VPhysics objects (moveable props, func_rotating etc.)
- func_brushes, anything that can be disabled and enabled
- Players retain filters set by triggers

**Comment by RabsRincon** [comment]
I labeled it as a bug, but it is indeed _just_ an unimplemented feature. I have created its corresponding trello card so we don't forget about it: https://trello.com/c/Gsb8nMLV/148-reset-entitites-on-run-reset

**Comment by lodyb** [comment]
I think this is also an issue with watching demo replays, should it reset the state when watching a replay?

Imagine that there is a map where the doors start locked and they get unlocked as you progress. I'm not sure if the demo player physically touches, uses triggers so I don't think the map will look the same as when it was played for real.

**Comment by Gocnak** [comment]
Well, I'm certainly intrigued by doing this, where it will set everything that can be toggled in the map back to its default state (position/rotation/enabled/disabled etc) upon entering the start trigger, and "unlock" them when you exit it.

If we generalize this, when watching a replay, the same thing will happen, so that way it guarantees a consistent playback. So no worries there. But the problem becomes, does doing this fuck up potential routes that players use already? Do mappers need to make the default position/states of entities deliberate? I'll be prototyping my idea of a solution soon, seeing if this is something feasible to apply to every map, or if it'll require further changes to maps with moving/toggleable ents.

**Comment by lodyb** [comment]
It would work well if the player started as soon as they spawned, even things like rotating walls with holes in (yes they exist in maps):

- surf_crystal
- surf_ny_superhappiest
- surf_funhouse

Things like that should be consistent if they reset on player death/timer restart. Rotating entities would line up the same every time assuming you surf at the same speed. The problem arises when startzone triggers are used, as there will be an arbitrary delay before the timer starts. What we would need is some kind of hook that can set the default state of problem entities at any given time. This could be hooked to the startzone onendtouch. This might not even be perfect then, if the startzone is not a flat plane.

Are start zones even required? What benefit do they provide where restarting on info_player_start falls behind?

Just some thoughts on the matter ;-)

**Comment by Gocnak** [comment]
Ideally these maps are going to be fixed to have all RNG elements of them removed, including rotating bits and doors and such. Most servers already do this, we plan to do the same.

Rotating bits have been agreed to be tedious, doors as well. Maybe a custom game mode can support this, but for default, bhop and surf, doors, rotating bits, and so on will be fixed to be consistent for every player.
