### ISSUE TITLE
Remove explosives impacts after a couple seconds

### ISSUE THREAD

**Issue by ghost** [momentum-mod/game#1049]
**What feature is your improvement idea related to? Please describe.**
The sticky bomb explosion impact is annoying and always takes my attention off the main sticky. I will make it so that the stickybomb impact gets removed after a couple of seconds.

**Describe the solution you'd like**
Once you place a stickybomb and it explodes, the impact will be removed in a couple of seconds (5-10).

**Comment by braem** [comment]
You can toggle these off https://docs.momentum-mod.org/var/mom_sj_decals_enable/

**Comment by CoopJax** [comment]
Yeah, but I also just want to make it so that it just goes away

**Comment by CoopJax** [comment]
This needs engine access.

**Comment by Gocnak** [comment]
Yep it does, but in a pretty weird way.

Source allows decals to fade out over time (see `$decalFadeDuration`):
https://developer.valvesoftware.com/wiki/Decals#Material_parameters

But the engine code since 2007 doesn't support it for some reason. So it'd need to be reintroduced, which is what requires the engine code.

**Comment by EthanV-3D** [comment]
Seems to be working in latest 0.9.18
Has been tested on our new explosion decals

**Comment by Gocnak** [comment]
Thanks for testing! Seems like Strata just had this from the get go?
