### ISSUE TITLE
mom_restart from console breaks run safeguards

### ISSUE THREAD

**Issue by Pyrt** [momentum-mod/game#1068]
**Describe the bug**
Running 'mom_restart' from the console disables the run safeguards that are set.

**To Reproduce**

1) Enable any run safeguard and enter a zoned map, pressing the reset current stage bind works as normal.
2) Run 'mom_restart' from the console and press the reset current stage bind in the map zone.

Video: https://streamable.com/vloj96

**Expected behavior**

The run safeguards should still be in place after restarting the map.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Latest develop branch

**Comment by braem** [comment]
Looks like this occurs because [`m_flLastTimePressed`](https://github.com/momentum-mod/game/blob/d52fc2f59a3a653e2df88d8f7f78a12b3851e76b/mp/src/game/shared/momentum/run/mom_run_safeguards.cpp#L126) is not reset on `mom_restart`/`ManualTeleport()`. This also occurs when reloading the map since `gpGlobals->curtime` is reset and `m_flLastTimePressed` is not. 

Both will require hooking into the map restart/reload functions to reset that properly. I think we can do that by making this a system? @Gocnak
