### ISSUE TITLE
Stickybombs don't fire when exiting start zone at the exact same tick

### ISSUE THREAD

**Issue by ghost** [momentum-mod/game#1108]
Report, details, and video by **False_**

**Describe the bug**
When exiting the Start Zone, if you fire a sticky at the exact same tick as you leave, the sticky will not fire.

**To Reproduce**

- Enter a Start Zone
- Fire a sticky on the same tick as leaving the start zone.

This clip shows it more clearly - watch the inputs display on the bottom right.
[Streamable Clip](https://streamable.com/hz2smy)

**Expected behavior**
You should be able to fire a sticky when you are leaving the Start Zone.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version

**Comment by braem** [comment]
Seems that this happens when holding down attack then releasing it _just before_ leaving the end zone; `m_flChargeBeginTime` is never `0` in `PrimaryAttack` when this happens.

**Comment by braem** [comment]
Had to do with releasing attack right after leaving the start zone. Starting a run resets the charge time to 0, and if u release attack right after it will not fire (because you now have 0 charge).

Solution was to store the previous charge time when it's reset and see if attack is released on next think.

Does this still occur?

**Comment by hexaflexahexagon** [comment]
can't seem to recreate anymore so i'll assume this was fixed properly until anyone else experiences it, closing.
