### ISSUE TITLE
Implement mom_restart_undo

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#1115]
The current run safeguards are nice, but occasionally one will hit their map restart button rather than stage restart button, or try to stage restart on a nonstaged map, resulting in a unintentionally lost run. This command would utilize the same system that mom_practice uses, and would put you back in the same location with the timer still running.

**Comment by Arkanoid0** [comment]
I haven't completely thought this through, but a simple position mark should be good enough, current safeguards should be sufficient for accidental resets, this is more for an intentional reset of the wrong type, keeping momentum or projectile state should be unnessisary.

What is required though is the players current filter state, but everything required we should get for free from the existing saveloc and practice implementation, with some possible refactoring of those systems to make their functions callable from elsewhere.

**Comment by Gocnak** [comment]
Concerns I have off the top of my head:

Replay file needs to *not* record going back into the start zone as this would absolutely break replays and playing them back.

Should there be a threshold of this? Like if a run is over a certain time allow this? I'm thinking about how we could nudge towards "did you mean to reset that run? press <key> to undo" (toggleable ofc) without being too annoying (every run restart).

The timer resets upon landing in the start zone. I worry that trying to hack this command in place greatly breaks a lot of the assumptions we have around run restarting and potential abuse. For example, landing in the start zone after doing mom_restart during a run would now *not* restart the timer, should this be shown on the HUD (timer, comparisons, etc) still? Undoing the restart also teleports the player out of the start zone which we've hard coded to also not start the timer, but I suppose we just check to see if the replay is still recording... We'd need a lot of testing efforts done internally on the branch if we end up going through with this.

Should there be any limitation to a number of undos people have? The timer will of course still be running so it's almost like watching a replay during the run I guess.

Where should the reset take them? Exactly where they were in the run or to the start of the stage if it's a staged map? We're going to need to make damn sure that they get reset properly either way in regards to targetnames and whatnot...

**Comment by hexaflexahexagon** [comment]
I'm not super huge on this idea but I also don't really like `mom_restart_stage` in the first place so that can be taken with a grain of salt most likely. This _feels_ like a small problem that can be fixed by a user changing their binds but, again, I don't really use `mom_restart_stage` so I wouldn't know for sure.

If implemented I would think replays should be handled similarly to when using `mom_practice` mid-run (not stopping the character and just acting as if all inputs were released), the only issue with that being you need to almost have 2 separate positions for the player or something? One where they are going to decide to use the undo command and then another where they are not going to use the undo command and will instead start a new run (or leave the map, stand in the start zone, etc...). Seems highly laborious to add and also very prone to bugs for the reasons that Gocnak listed, though the replay refactor is planned regardless so it's not too out of the question.

Similarly the command itself should probably just take the user back to exactly where they were (again like `mom_practice` does), though most of the time that would be synonymous with just failing the stage.

As soon as the user leaves the start zone after resetting the previous run should no longer be recoverable. Watching a replay or going into spec should also forfeit undo-ing back into a run (though maybe not, as you can already do those things mid-run anyways?)

**Comment by braem** [comment]
Completely forgot about replays. This is much more trouble than it's worth imo.

**Comment by Arkanoid0** [comment]
Teleporting out of the start zone should never start the timer anyway, as the only possibilities are to another start zone, either stage or bonus, or via this command, so there shouldn't exist any edge cases where you teleport out of a start zone via mom commands where you also want the timer to start.

A reasonable compromise might be a small (5-10s) window after a reset to undo, as if you want to undo you would know immediately, and if you don't you would just start a new run.

As for reset position, previous location is likely the best, as assuming the player is using the reset safeguards, they are also most likely to be standing somewhere already, as most gamemodes have places one can stand between stage/course triggers(or have intermediate fail triggers like rj/sj/bhop), surf is really the only gamemode where this assumption doesn't hold, which would likely result in the player dropping to a stage fail trigger.

This brings up a secondary consideration, whether we give the player back his entire run state, including momentum and projectile state. If we assume the functionality is like mom_practice then current implementation says yes, (which conveniently also answers the previous question), but i could see this going the other way.

For replays, my instinct is to say that a replay should be a recreation of what the player saw/did, so if they went spec/mom_practice/watched a replay the resultant replay would include that. This does result in the potential for recursive watching of replays which is strange, but I think this question is better asked when the replay refactor happens, and if this was to be implemented it should be before the refactor to ensure consistency and such.

**Comment by Gocnak** [comment]
Let's instead focus on preventing accidental resets with safeguards as much as possible, including some hard-checks (not-toggleable popup) after runs hit a certain threshold of progress. While resetting after an oopsie is nice, it dismantles any need for any safeguard whatsoever.

**Comment by Arkanoid0** [comment]
> While resetting after an oopsie is nice, it dismantles any need for any safeguard whatsoever.

I disagree that being able to undo a reset completely removes the want to not reset accidentally in the first place, but i agree having only one is sufficient, even if both would be ideal, and run safeguards are easier to implement than this idea in the first place.

That said, some players will dislike safeguards enough to completely disable them, and a secondary system is in my opinion worth the effort. Additionally, i think nearly all the work needed for this to work will have already been done by the time 1.0.0 rolls around with the work getting put into practice mode and zones in general. It might be worth at least putting up a community discussion on the topic of resets and safeguards to really figure out what people want and would use.

**Comment by hexaflexahexagon** [comment]
i still agree with what i wrote 9 months ago and with what gocnak said, this is not something that we should be pursuing.
