### ISSUE TITLE
Broken mipmaps with -forceallmips on textures without full mipmap chain

### ISSUE THREAD

**Issue by bltech** [momentum-mod/game#1123]
**Describe the bug**
Certain surfaces on the map that change between being opaque and invisible. Depending on angle, the momentum trigger teleport texture is shown instead (obviously without having showtriggers enabled)

**To Reproduce**
- Boot up the game on linux
- Start sj_naissancE
- Observe the wall above the first jump

**Expected behavior**
It should look like [this](https://www.youtube.com/watch?v=wJOlGrP5HFY)

**Screenshots**
![20201031193414_1](https://user-images.githubusercontent.com/19615431/97787497-e8df2980-1bb2-11eb-9352-34b58d783b5d.jpg)

**Desktop/Branch (please complete the following information):**
 - OS: Linux
 - Branch: 0.8.6 Steam

**Additional context**
https://discord.com/channels/235111289435717633/235125108656701440/772168477322248192
Might be related to mipmaps, as it appears to also happen on Windows with `-forceallmips`

**Comment by braem** [comment]
All mipmaps are buggy with `-forceallmips` launch option and possibly for the linux build.

**Comment by McGravel** [comment]
May relate to these textures not having a "full" mipmap chain all the way down to 1x1 or however low it goes.

SprayMaker5000, a tool used to make textures with custom mipmaps warns about having mipmaps lower than 32x32 resolution not being used - this is usually the case, but with `-forceallmips` it will load the rest of them.

In this case, the rest of the chain is missing, so my guess is that the engine must be grabbing mips from another loaded texture instead, perhaps like some sort of overflow in the VRAM perhaps? 🤷  Something to look at with a graphics debugger maybe...

**Comment by McGravel** [comment]
Looks like my guess may be correct, or at least close to the truth:
![](https://i.imgur.com/a2nWoBC.png)

**Comment by McGravel** [comment]
Renaming issue to be a bit more accurate; it also is not specific to `sj_NaissanceE` so the mention of it has been removed.

**Comment by bltech** [comment]
Do note that at least on Linux it doesn't require -forceallmips to happen

**Comment by braem** [comment]
Still occurs on Chaos, however now all mips are loaded on Windows versions higher than XP (Vista onward). Because they're forced on in Linux too it's safe to assume all mips will be loaded for the vast majority of players.

**Comment by braem** [comment]
CSGO (and Chaos) always loads the full mipmap chain (all the way to 1x1) when on ToGL or Windows Vista & above. Not going lower than 32x32 turned out to be a Windows XP limitation, which Chaos will not support. `-forceallmips` launch option has been removed now as all mips are loaded.

The map in question looks like this on Chaos, 0.8.7 linux, and 0.8.7 `-forceallmips` as it only had mips down to 32x32, so 16x16 and lower were garbage data. Has been corrected: https://github.com/braem/sj_NaissanceE/releases

Mappers can still load down to only 32x32 by using the mostmips textureflag. I think it's safe to have mappers use textures with this or full mipmap chains now so I'll close this.
