### ISSUE TITLE
Add WR/PB hud element

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1180]
This issue needs peer reviewed before anyone works on it to determine if it's even desired.

**Is your feature request related to a problem? Please describe.**
Some players are used to seeing the WR, WR holder, and their PB on the screen from servers. While you can use tab to display the times manually, some people simply prefer having them on screen

**Describe the solution you'd like**
Add a panel that displays the WR, WR holder, PR, and other related information. Could possibly be tied into the splits feature that is already planned (and would have a hud element). This should also have a toggle cvar that is in the settings menu so that people who dislike the change can remove the element themselves.

**Additional context**
Suggested by nevier in discord.

**Comment by Gocnak** [comment]
Not going to be done, we want to centralize our UI and we aren't a plugin. Comparisons panel will update to have more info about the run you're comparing to (time and who did it) so that's the extent we'll go to support this. It would be extremely messy to have individual label panels all over the HUD.
