### ISSUE TITLE
Game not mounting custom folder

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1220]
**Describe the bug**
The game no longer mounts the custom folder after the chaos port.

**To Reproduce**
1. Add any file in custom
2. Load the game
3. Nothing has changed

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: 0.8.8-rc

**Comment by VortexParadox** [comment]
The mounting system ignores the wildcard `*` present in the `gameinfo.txt`. So it get's treated as a folder name.
Removing the wildcard so it's just `custom\` will load as if it was any other `game` folder. This means that in order to mount something it'll have to be changed to `custom\materials|models|scripts|etc.`, removing the advantage custom had allowing the user to organize their files
