### ISSUE TITLE
VTF Resources cause VTFs to not load or hang the game

### ISSUE THREAD

**Issue by ghost** [momentum-mod/game#1223]
**Describe the bug**
Certain VTF files appear to fail to load or worse still, hang the engine.
This affects the game as well as Hammer in an identical manner.

**To Reproduce**

### Non-loading VTF:
[Example Non-loading VTF](https://cdn.discordapp.com/attachments/409531321455607808/807796668657172520/pbr_debug_n.vtf)

- Create a VTF in VTFEdit with the "Information Resource" enabled.

    My settings were as follows:  
    ![](https://cdn.discordapp.com/attachments/409531321455607808/807794912543375370/unknown.png)

- Use in a material, the VTF will not load, and produce an error in console.

### Hanging VTF:
[Example Hanging VTF](https://cdn.discordapp.com/attachments/409531321455607808/807804871842725898/pbr_debug_hang.vtf)
- Create a VTF with the "LOD Control Resource" enabled.

    My settings were as follows:
    ![](https://cdn.discordapp.com/attachments/409531321455607808/807786940459646976/unknown.png)

- Use in a material. 
   - The game will hang if you try and load a map with this texture.
   - The game will hang if you try and reload materials after creating a VTF with the affected Resource.
   - Hammer will hang on map loading if the VMF references an affected material using this texture.
   - Hammer will hang if you tab back in after creating a VTF with the affected Resource in a currently used material.
   - Hammer will hang if you attempt to apply the affected material to a surface.

**Expected behavior**
The game should load the VTF regardless of the presence of either Resource.

**Screenshots**
N/A

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8-rc

**Additional context**
N/A

**Comment by SlidyBat** [comment]
Regarding information resource issue, seems to be behaviour of CS:GO as well. The engine expects that the image resource is the last one in the file, and only loads data up to the end of that resource. Having resources past that is considered an error.

Was hesitant to fix this, since it feels like an issue with the tools rather than engine, but seems TF2/CSS allow this, so I did same thing.

For the LOD control resource issue, I can't replicate. Your linked material seems to load fine in game.
