### ISSUE TITLE
Stickybomb rollers sometimes go through floors

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1234]
**Describe the bug**
Sometimes stickybombs go through floors (maybe walls too?) when they are roller. 

**To Reproduce**
1. Shoot stickybombs on a thin roller floor (like on the vert in sj_arugula)
2. Witness vphysics at its finest

**Expected behavior**
Stickybombs should not go through solid objects!

**Desktop/Branch (please complete the following information):**
 - OS: Window
 - Branch: 0.8.8-rc

**Additional context**
Needs further testing whether this is only with `func_brush` or `clip_vphysics`.

**Comment by hexaflexahexagon** [comment]
I made a test map and the bug happens reliably* at `setpos 395.709869 505.674103 324.031250;setang 37.092022 -1.625727 0.000000`. The map includes func_brush and func_clip_vphysics but it seems like it only happens with func_brush. Also worth noting that this doesn't happen in TF2 or SDK Momentum to my knowledge.

*reliable-ish as the bug only happens about 30-50% of the time at the same exact position. Probably something to do with random rotation and vphysics collision? Since random sticky firing doesn't exist in Momentum like it does in TF2. 

Video: https://streamable.com/ixbnei
Download: https://cdn.discordapp.com/attachments/285188007353516033/813326245331992586/sj_rollerbug.bsp

**Comment by braem** [comment]
I have a hunch this is related :x 
https://cdn.discordapp.com/attachments/781445540386832384/813366436159946792/2021-02-22_03-06-34.mp4

**Comment by Gocnak** [comment]
It was the physics environment not ticking at the same rate as tickrate, which 2013 does. Fixed.

**Comment by Gocnak** [comment]
Alright so on further investigation, it's still happening but only because func_brush are created with a dynamic VPhysics object and func_clip_vphysics is created with a static one. I worry that either this is in VPhysics (closed source to us still) or maybe it's in how physics objects are updated on this branch.

VPhysics is the same in TF2/SDK Momentum, but it is also a different version of the library... I hope to solve it soon, but I don't know if we can just change the func_brush to be just func_clip_vphysics when porting the maps.

**Comment by braem** [comment]
Explanation of the fix: https://ptb.discord.com/channels/235111289435717633/733950694209355816/847734071249469460

![image](https://user-images.githubusercontent.com/5162166/119945632-b8524900-bf63-11eb-919a-7a37e30d3342.png)

**Comment by braem** [comment]
Not sure if we want to close this one as we implemented a bandaid fix and it may be revisited if we ever get VPhysics code. New label perhaps? Resurrect `Requires engine access` to be `Requires VPhysics access` lmao

**Comment by Gocnak** [comment]
A proper fix was implemented as the performance parameters passed into vphysics were slightly different. Needs testing if the behavior is exactly like 2013 now.

**Comment by patrickmoc** [comment]
Could not reproduce the bug with the sj_rollerbug setup on the most recent build. It seems consistent with the public evaluation build.
