### ISSUE TITLE
Brian Charles' Parallax-Corrected Cubemaps's implementation on other source base mod

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [momentum-mod/game#130]
Hello, I know that I do not count as a problem but I have loved its mod and the gameplay absolutely all aspects of it. But I have curious how it is that they implemented the "Parallax-Corrected Cubemaps", because I have not found how to implement it In my mod I would be very grateful: D

**Comment by Gocnak** [comment]
Brian Charles has two READMEs included with the download from his video. It isn't the most straight-forward instructions, but I followed that in order to implement it. I don't have an updated guide for you, but you can follow the following commit trail to see what code I specifically changed to implement them:

c682ca30eba90fb9e6f7fa384ac93e273fa917ea
6a870379f8ba722e9b406ce14919e0abc4c5b75b
43640896344bbf115b49ac2163e8b048bb292bb5
2cefdcd7d70548f47a94711641e4bcd5fb642a37

If I could suggest something: **_do this on a beefy computer_**, as you're required to compile a custom `lightmappedgeneric` shader, which takes a LONG time (upwards of 30 minutes per bake).
