### ISSUE TITLE
Overlapping transparent textures don't render properly

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1309]
**Describe the bug**
Maps with transparent brushes that intersect with each other will often have a very hard time drawing one on top of the other, resulting in visual errors such as in the video below. This issue exists in TF2 and can be somewhat worked around by using different shaders. The only one that does not have this issue is $alphatest, the rest on this list under Transparency do. https://developer.valvesoftware.com/wiki/Category:List_of_Shader_Parameters

**To Reproduce**
1. Load a map such as jump_anxiety (downloadable from https://tempus.xyz/maps/jump_anxiety_a9)
2. Go to an area where the bug happens (`setpos 2107.682373 13604.003906 12808.662109;setang 4.123756 -56.333920 0.000000`)
3. Look around slightly and notice the visual issues

Video example: 
https://www.youtube.com/watch?v=fSepEQgKTQ8
or
https://user-images.githubusercontent.com/62961532/115326826-e91cb280-a15b-11eb-88fa-530142f37d63.mp4

**Expected behavior**
The two brushes should not be fighting eachother (i.e., it should be easily possible to tell where the intersection of fence texture and black texture in the example video is)

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: 0.8.8

**Comment by SlidyBat** [comment]
Issues with overlapping transparent textures are common with almost every game engine. Might be possible with a lot of effort to do some automatic splitting of the geometry or use some state-of-the-art technique to fix this, but really the simplest solution is to just avoid overlapping these objects in the first place.

In this particular case, the planes can be split up so that none of them intersect. The barbed wire material could also be changed to be alpha tested instead of transparent.

I'm going to be closing this as a wontfix.
