### ISSUE TITLE
Add preset -mapping launch option

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1352]
**Describe the solution you'd like**
Recently we added a launch option when starting the game through steam that lets you automatically toggle panorama without having to add/remove the launch option, see below. As we already have this menu (and bit the bullet of annoying people by having this popup by default), there's no harm in adding other commonly used launch options there. Specifically, `-mapping` is the most commonly toggled. 
![image](https://user-images.githubusercontent.com/62961532/120120963-f1123e00-c16e-11eb-9bcc-753c2dba16e1.png)

This doesn't let users stack options unfortunately but without adding every single combo I think this is still a fairly good compromise as most people typically will care about 1 option at a time.

**Describe alternatives you've considered, if any**
We could also add the Dx11 option which would be nice, especially considering the parameter is fairly obtuse (`-shaderapi shaderapidx11`) and is hard to remember if you want to enable it.

**Additional context**
Suggested by Aart in discord

**Comment by lvaness** [comment]
-dx11 is an alias for -shaderapi shaderapidx11 now

**Comment by Gocnak** [comment]
When Panorama becomes the default, we can replace the (Panorama) option with -mapping.

**Comment by jason-e** [comment]
Is there a reason mapping mode is a launch option and not an in-game thing?

If the only launch presets would be "normal" and "mapping", it might be better to leave mapping as just a launch flag because it's slightly annoying to have to confirm which preset to use every time you launch the game (when using the play button in Steam). 99% of users will not ever need to use mapping mode.

**Comment by Gocnak** [comment]
On boot, when it loads/filters FCVAR_MAPPING convars, it filters them out based on the launch option (convars aren't loaded yet). It's mainly so that there's a distinct mode to boot in that won't load AC/try to submit runs or anything, and is more "open" to mess around with specific game changing variables.

People should not have to boot into mapping unless they know what they're doing, really. I'm not even really a fan of it being a launch option, makes it seem really messy for like 99% of our players.

**Comment by hexaflexahexagon** [comment]
i think the issue is how you define "unless they know what they're doing." lots of people need `-mapping` for various test cvars (conc the problem child) and those uses will vanish closer to 1.0.0, but also many people need `-mapping` to make actual maps. what `-mapping` commands exist that absolutely need the separate launch option? if there aren't many maybe we could consider trying to move those over and renaming `-mapping` to something that truly very few people will need, akin to `-insecure` in traditional source games?

only thing I can think of is the zoning tools which we may be able to work around. perhaps they're disabled on official maps only? idk how easy of a check that would be

**Comment by Gocnak** [comment]
This will be revisited in the future, as `-mapping` will be removed in favor of game-side and server-side checks of settings. Game-side will warn (but still record and not submit), and server-side will validate against known goods. I will be closing this issue as, when it's removed, this launch parameter will no longer be needed.
