### ISSUE TITLE
Panorama settings menu

### ISSUE THREAD

**Issue by SlidyBat** [momentum-mod/game#1360]
Has already been mostly implemented, but few things remain:
 - [x] Speedometer settings - pending UI mockup (#1013)
 - [x] Color picker - need custom panel (https://github.com/momentum-mod/game/issues/1520)
 - [x] Model preview - need custom panel
 - [x] Decal preview - can probably be done with UICanvas, or custom panel

Possible that some of the layout will also be changed when gamemode-specific settings are decided on.

**Comment by tsa96** [comment]
One last thing: gamemode-specific settings. Many players have keybinds and other settings per each gamemode and it would help to have accessible UI for this besides just gamemode configs). 

As we've discussed, what seems ideal is having one or more of the settings panels include a dropdown box that lets you select a gamemode, and then any settings changed there will overwrite the base settings. Overwatch has a similar system that I like a lot, attached in a video demonstrating it.

To get implemented we'll need UI mockups, then for the dev team to decide how the specific settings should be stored. If that was in a file relatively accessible to users that'd be nice, to allow for a mixture of configuring gamemode settings within the menu, and using configs/whatever equivalent replacement.

https://user-images.githubusercontent.com/35813309/121093919-abe0b280-c7e5-11eb-9139-cbe46bf1d218.mp4

**Comment by decl0s** [comment]
Color Picker Mockup. (The background of the panel should have a more contrasting color to not look like the background. Switch Save / Cancel buttons to => Cancel / Save, updated version is on the zeplin)

![Color Picker](https://user-images.githubusercontent.com/49877244/126101183-9dfb2091-2d1e-4d37-89f1-4061f86d3b62.jpg)

Speedometer Settings w/ [Range Based Colorization Options](https://github.com/momentum-mod/game/issues/828) (Might want to add a preview panel to the speedometers)

![Settings – Speedometer Settings](https://user-images.githubusercontent.com/49877244/126101339-e55db35b-30a9-4769-a0cb-5f3d9ce123b0.png)

Decals Preview Mockup

![Settings – Decal Preview](https://user-images.githubusercontent.com/49877244/126103618-2a921bf1-8b47-4f6e-a91f-6dbf66a6f4df.png)


All screens have been pushed to Zeplin. Color picker is on the "UI/UX Components" screen.

*Notice the changed top right. Now has Apply / Discard buttons and a gamemode selection dropdown. (Buttons should only be colored while hovered or clicked probably. Should just be the transparent white otherwise)

**Comment by tsa96** [comment]
Also, we want settings for the crosshair, right?

**Comment by Gocnak** [comment]
> 
> 
> Also, we want settings for the crosshair, right?

https://github.com/momentum-mod/game/issues/1107

**Comment by tsa96** [comment]
Color picker and decal preview fully integrated in settings-styling branch on green, just need speedo now :)

**Comment by hexaflexahexagon** [comment]
Main settings panel work is done, any new features or bug reports can be separate cards
