### ISSUE TITLE
Conc beep pitch shifting affecting fuse timer/handhelds

### ISSUE THREAD

**Issue by zike1017** [momentum-mod/game#1369]
**Describe the bug**
Currently there's some variance in the pitch of the conc grenade beeps so people aren't constantly hearing the same sound. This variance in pitch however is affecting the fuse timer and also handhelds. Setting a constant pitch value for ConcussionGrenade.Timer in game_sounds_momentum_weapons.txt fixes this issue.

**To Reproduce**
1. Attempt a handheld conc off the ground using only audio cues
2. Be sad you go no where
3. Change ConcussionGrenade.Timer pitch to a single value
4. Attempt a handheld conc off the ground using only audio cues
5. Go zoom and handhelds work as expected

**Expected behavior**
The pitch shifting should not impact the timer in any way. It is still desirable to have some variance in the pitch, but this variance should not impact the grenade itself.

From thorough TFC boomer investigation the baseline pitch should also be 101 and not 100.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam

**Comment by brunch875** [comment]
Baseline pitch might need to be measured again when #1370 is resolved.

**Comment by brunch875** [comment]
Tested, resolved. 100 perfectly aligns to last beep, so it's preferable.

**Comment by hexaflexahexagon** [comment]
like the above comment mentions this should _actually_ default to 100 rather than 101 ideally, but that should be a very simple change to make. after that this can be closed.

e: and since this was not a unanimous agreement on 100 i'll also add here that anybody can change this on their client if they so choose. 
1. copy `momentum/scripts/game_sounds_momentum_weapons.txt` into `momentum/custom/asdfsfd/scripts/game_sounds_momentum_weapons.txt`
2. find the "ConcussionGrenade.Timer" block
3. edit "pitch" from 100 to whatever your desired value is

this may cause some sounds to break after an update releases that changes this file but you can simply delete your existing custom file and recreate it to fix these.

**Comment by Gocnak** [comment]
Pitch was changed to normal. Closing this for now until the community consensus is chosen: https://forum.momentum-mod.org/d/70-conc-changes-megathread/14
