### ISSUE TITLE
Standing on/ jumping off a conc on the ground does not give the correct knockback

### ISSUE THREAD

**Issue by zike1017** [momentum-mod/game#1372]
**Describe the bug**
Compared to TFC, getting height off a conc on flat ground from either jumping or standing on it is noticeably less. From my testing, TFC you can get a height of about ~184 units while standing right on top of a conc, while MM you get only ~160 units.
This is an issue because it prevents the player from doing the common technique of jump off conc -> handheld.

**To Reproduce**
1. Prime a conc and immediately prime a 2nd
2. jump off the first conc as it explodes
3. try and fail to get any height from the 2nd conc as a handheld
4. repeat in TFC and notice the significant height gain from the handheld

Here is a comparison of the 2 techniques in each game:
https://streamable.com/vwv9mk
Here is that same video slowed down:
https://streamable.com/bhfjx1

From these two clips it looks like the delay before you can throw a conc (and thus prime a 2nd) is correct. However, the 2nd conc clearly detonates quicker in TFC. This is very odd considering that in this comparison clip MM concs have a fuse of about 3.8 seconds compared to TFC's 4.0 seconds. This is seen in how the first conc detonates in MM before TFC. 

**Expected behavior**
The technique of jump off conc -> hh should be doable in MM. I've also linked a simple test map where if you go in between the 2 gray pillars to your right at spawn you can test height from standing on a conc. The left one has a tele 160 units above the floor. This is the current MM max. The spot to the right has a tele 184 units above the floor. This is hittable in TFC, but not currently MM. I can only assume this discrepancy contributes to the fact you cannot jump off a conc -> handheld.
https://mega.nz/file/UggWyawZ#0ue6EOe5OaB-bXpXv9B3zdQO5j8uSAilQIbqzUjrsdo

**Desktop/Branch:**
 - OS: Windows
 - Branch: Steam version

**Additional context**
From my understanding the only things that would affect this are the point on the player from which knockback is calculated (currently origin?) and the amount of knockback. The amount of knockback concs give seems to be accurate. If the point at which calculations are done from is the only factor, might be easiest to make this a cvar and let concers mess around with it until it's right.

**Comment by nmalmrose** [comment]
https://www.desmos.com/calculator/mr90gbhq2o
The red points are TFC, the blue points are MM
X is the vertical units a stationary player is standing above the conc. Y is height after the conc explodes.
45 units is max height for a jump in tfc, and 280 is max distance a conc will hit affect you in TFC.
70/140/210/280 is just max distance broken up

[Test Map for MM hosted on Discord](https://cdn.discordapp.com/attachments/719632195982983308/854244947610697748/conc_testheight.rar)

The room you spawn in is tuned for MM testing. The room above the room you spawn in are the heights that a player achieves in TFC on an identical map.

**Comment by Mac-tf2** [comment]
TFC concs are a singular point without a physical hitbox around the grenade model. Momentum concs are a physical ball and the origin of the explosion is potentially a few units off the ground instead of flush with the surface because of this. This might account for some of the reduced knockback from grenades thrown on floors.

**Comment by hexaflexahexagon** [comment]
This is better but not yet finished on the newest update. The gray pillar test mentioned in the issue passes now (likely due to making conc's 0.0002 units big) and jump -> hh is slightly better but it still doesn't go as high as in tfc.

**Comment by zike1017** [comment]
I made some comparisons videos as well as a test map to showcase the difference from a jump off 1 conc -> hh. Instead of actually jumping I start standing on a block 45 units high (the maximum jump height). 

TFC: https://streamable.com/tvojt6
MM: https://streamable.com/z9ltkk
Test map: https://mega.nz/file/NpoxVC7R#qpEPE7MdTzhNxqBhjBv2X1X1jQj-d81rhlFS8gYx4MY

From this testing it looks like in TFC you can gain about ~1456 units of height, and in MM you can gain about ~1104 units of height. These numbers aren't exact because of the concs not being in the exact same spot every time, and in TFC you cannot perfectly chain prime like you can in MM. In the attempt in the video for TFC I would have gone maybe 20-30 units higher had I not had the teleport there. Regardless, there is still clearly a big difference in the amount of height gained.

In the test map you'll also notice some pillars near the corner for where the setup is. The shorter pillar is roughly what is gained in MM and the larger pillar is roughly what is gained in TFC.

**Comment by Mac-tf2** [comment]
Thrown grenades in TFC have a longer fuse time than handheld grenades. The values from testing briefly seem to be anywhere between 3.88 seconds and 4 seconds for a thrown grenade because of engine jank. Handhelds are consistently 3.8 though.

This makes the handheld detonate earlier in relation to the thrown grenade, meaning the hh will detonate while you still have some vertical momentum. Adding at least a minimum of 0.1 seconds to thrown grenades seems to work okay from my limited testing, but if you go that route for fixing it the number may need some fine tuning.

EDIT: more accurate testing: https://discord.com/channels/235111289435717633/719632195982983308/860277964499058779

**Comment by Mac-tf2** [comment]
If what hlstriker was saying is true that it tends to lean closer to the upper/lower bounds more frequently, I think it makes sense to keep it as the lower bound consistently since the upper bound is gross. Somewhere in the middle feels only slightly less gross than the upper bound. 

3.9 feels good to me with the TFC sound file for beeps, so if that still feels off to some people, it must be a sound issue.

**Comment by hexaflexahexagon** [comment]
I was able to get about where the TFC video did on `conc_exist` now, and I was also able to hit the tele underneath the taller gray pillar, so I'm going to consider this issue resolved. 

![image](https://user-images.githubusercontent.com/62961532/124609153-6099de00-de3d-11eb-9a11-a9c5404a4269.png)
