### ISSUE TITLE
env_hudhint does not display hud hints (on both panorama and vgui)

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1376]
unsure of the issue, however hud hints don't seem to be displaying properly.

![image](https://user-images.githubusercontent.com/62808028/122326410-2ca95800-cf24-11eb-8b18-0200c532ec71.png)

**Comment by Gocnak** [comment]
VGUI one doesn't work because the file was not included because VGUI is going to go die in a fire soon.

Panorama one doesn't work because we don't have a Panorama HUD yet, but will be added by 0.10.0. Kicking back to 0.9.2 for now, for verifying when we add the HUD that we get this panel back.

Map to test: https://cdn.discordapp.com/attachments/678782392797888524/865517866257481748/hud_hint_test.bsp
