### ISSUE TITLE
How Do You Implement The New GameUI?

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [momentum-mod/game#142]
i'm curios because you remove the old GameUI2 so, how did the engine use the mod's GameUI?

**Comment by Gocnak** [comment]
Using [Alien Swarm's GameUI code included in its SDK](https://github.com/NicolasDe/AlienSwarm/tree/master/src/game/client/swarm/gameui), we were able to create the GameUI project that compiles the correct file to replace the existing one. After compiling the new GameUI, it's just a matter of replacing the old file that gets loaded, for SDK projects it'll be in Source SDK 2013 Multiplayer/bin/ (where the tools are also found).

We only got rid of GameUI2 since this new module basically encompasses the code that was inside of it. And our code doesn't fully utilize all of GameUI, only the parts we need.

**Comment by Gocnak** [comment]
You can look at #141 for the commit chain to follow in order to do the exact same thing for your project, if you'd like. I'll close this for now, if you have any further questions on the matter feel free to either [contact us](https://momentum-mod.org/contact) or [join our Discord server](https://discord.gg/wQWkRb6) for more immediate feedback.
