### ISSUE TITLE
Panorama Text Input Animations Are Weird

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1432]
**Describe the bug**
Hovering a text input in panorama animates the background color between 3 different ones. Slidy thinks this may be a CS:GO implementation mishap; needs to maybe be checked with CS:GO reference code.

**To Reproduce**

1. Open settings
2. Hover over a text input
3. See weirdass animation

https://user-images.githubusercontent.com/5162166/125206950-b9131600-e257-11eb-8d5d-adffe5533388.mp4

**Expected behavior**
Animate smoothly between default (non-hover) bg and darker/lighter BG to show hover state properly. Check CS:GO for what theirs looks like for proper impl.

**Desktop (*please complete the following information*):**
 - OS: Windows
 - Renderer: DX9 (Default)
 - UI: Panorama

**Comment by lvaness** [comment]
Weirdly, when I replaced the default white background color of the box with a gradient that has the same white color at both ends, the animation works fine. The reason CSGO doesn't have this issue is that the box just doesn't have a default bg color.

There might be an issue with the interpolation of the transition.

**Comment by tsa96** [comment]
This is just some bad styling in the ChaosSettingsSlider, will be fixed in settings PR

**Comment by hexaflexahexagon** [comment]
looks good now
