### ISSUE TITLE
Speedometer units (MPH/KMH/Energy) only works for Absolute Speedometer

### ISSUE THREAD

**Issue by Kanisof** [momentum-mod/game#1458]
**Describe the bug**
When choosing " speedometer units " for example mph/kmh/energy, it doesn't work for anything except Absolute Speedometer. Vertical/Horizontal is still displayed in UPS only 

**To Reproduce**
Try setting the units to mph/kmh/energy for vertical/horizontal etc type.

**Expected behavior**
Show the correct units. 

**Desktop (*please complete the following information*):**
 - OS: Win7
 - Renderer: DX9 Default
 - UI: VGUI

**Comment by Gocnak** [comment]
@braem Is this issue still prevalent on Pano speedo?

**Comment by hexaflexahexagon** [comment]
doesn't look like it, though this is with editing the vdf file directly and not by using the settings menu (since that doesn't exist yet). if anything like this pops up later we should probably just open a new card.

![image](https://user-images.githubusercontent.com/62961532/138027504-1110c33b-7f76-483d-8e39-bd934822eaa1.png)
