### ISSUE TITLE
Change default maxvel in bhop

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1473]
Apparently most bhop servers uncap/raise maxvel by default rather than keeping it at 3500 like we currently do. We should increase it to something like 10000 since that seems to be whats most desired

**Comment by jason-e** [comment]
I've been managing bhop stuff for Horizon Servers for 4-5 years now and this is the first I've heard of globally raising the max velocity for bhop. I wanted to know more about the state of maxvel on bhop so I did some investigating.

Out of all the top runs for each of Horizon's 800+ bhop maps, only 24 maps even reach or get very close to 3500 velocity (horizontal):

- 7 of these either already increase the max velocity, or have an explicit recommendation to by the author on gamebanana (ArcticPanda maps).
- Of maps that are actually limited to 3500, I noted about 6 of them would probably get a meaningful benefit from an arbitrarily increased max velocity.
- I noted 9 maps which could benefit from an increased max velocity, but not in a meaningful way. Almost all of these came down to a booster at the very end of the map where an increased max velocity would make the ending a fraction of a second faster, but without changing the optimal route at all.
- The last 2 maps out of this set ***may actually be worse off*** with a higher max velocity. These were bhop_arcane -- where increasing the cap allows for more speed from the cannon, which already gives a hardly manageable amount of speed -- and bhop_2flocci2furious -- where increasing the cap would only make the end surf slightly faster, but also may make it unnecessarily easier even for casual players.

I would assume most mappers build their maps under a max velocity of 3500, and while increasing the max is sometimes a beneficial option they overlooked, other times increasing the cap can make the map worse.

Max velocity only comes into play on about 3% of maps, and arbitrarily increasing the max velocity may only be significant on something like 1% of maps, so I think the smarter and safer option is to increase the max velocity deliberately on individual maps rather than globally.

**Comment by Gocnak** [comment]
Momentum currently sets it to 100,000: https://github.com/momentum-mod/game/blob/develop/mp/src/game/shared/momentum/mom_system_gamemode.cpp#L111 and this is still in Chaos. This is on top of 1000 AA as well.

I'm actually not even sure the original intention behind this change, this was implemented in prehistoric/wild wild west times of ~2014-2015 Momentum development.

This might be why arcane's booster is kinda crazy in game too.

In retrospect, I think the 3500 cap with each map increasing it via a zone property would be perfectly fine with me.

**Comment by jason-e** [comment]
Also, after more Discord discussion I should clarify for anyone following this that I'm not advocating for players to be limited to 3500 in general, just that 3500 should be the starting point which is then changed when we review a map to be added. In practice players will probably never know the difference, but in case something is missed during map review, this way is safer because lowering the limit on a map already in the wild is destructive (people go slower than they are used to and recorded runs probably have to be removed).

**Comment by jason-e** [comment]
After more thought, I think it might be better to leave the max velocity high as the default. The main example against this was bhop_arcane, but I now realize we actually just need a version with the original cannon and the velocity cap is not really relevant there. I would be surprised if keeping the cap high caused any issues, and it would save the work of evaluating maps to see how fast they can be, where things can be missed.
