### ISSUE TITLE
Panorama Leaderboards Panel

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1514]
### What feature is your improvement idea related to?

Panorama port

### Describe the solution you'd like

See Zeplin for mockup. Probably will require web work?

**Comment by tsa96** [comment]
Styling has been pushed. A couple of things for you to look at Goc:

- We agreed that defaulting to the Global tab for recognised maps makes sense, which I do in XML and JS now, but I believe there's some C++ that's expecting it to be the Local tab at first.
- Pressing ESC when the leaderboards hud is open will open the main menu, rather than close the leaderboards, to then close the leaderboards you then have to press ESC to close the main menu, then press tab to close the leaderboards. This feels very unintuitive for me and I'd just expect ESC to close the leaderboards. Maybe worth letting people play with it first and see what they say, I suspect we'll be asked to have ESC close it though.  We spoke about how to do this a little bit, and whilst we can handle the "Cancelled" event from hud_leaderboards.js but the mainmenu seems to get to it first, you said you'd have a look at it.
- Behaviour of times can be a bit weird switching between tabs, especially from one local tab to another, as timesFiltered doesn't get called then. The JS logic for it is place, just a matter of when the onTimesUpdated method gets called.
- I can't get the author credits panels to react to oncontextmenu events. I've tried giving them hittest + hittestchildren, their parent/parent's parents etc hittestchildren, acceptsinput, and nothing. onmouseover and onactivate work, so for now I'm just using onactivate.

**Comment by hexaflexahexagon** [comment]
looks really nice! any other minor issues that may pop up can be new cards
