### ISSUE TITLE
Panorama console prioritizes autocomplete over fully typed command

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1527]
### What feature is your improvement idea related to?

Typing a command and then hitting enter (such as `quit`) will instead autocomplete to another command if available (like `quit_asdf`) when intuitively it should simply input the first command. I don't believe this is what vgui's console does but I haven't tested it super precisely. 

### Describe the solution you'd like

Make:
1. Type `quit`
2. Hit enter

Result in the game quitting rather than autocomplete taking priority and filling out `quit_asdf`

**Comment by granis48** [comment]
Adding onto this issue I noticed that scrolling through the autocomplete list is different to the way it was in vgui too.  
  
E.g whenever i wanna turn sv_cheats on in css/csgo i would type in "sv_chea", downarrow to autofill it to "sv_cheats " then add the 1 and hit enter. What happens now when i do that is It'll enter "sv_chea" but hitting down only scrolls in the autocomplete list (which only has one entry here btw) and wont actually fill anything in, then i hit 1 and enter resulting in this: ![this screenshot](https://user-images.githubusercontent.com/52294733/136416569-1cc25915-e1a7-4829-879b-ce3f2dada26c.png)

The expected behavior would be skipping the need to hit enter to "fill in" the autofill suggestion and instantly filling it as you scroll down keeping the list as the original till i enter something else in the input field.

**Comment by hexaflexahexagon** [comment]
the original behavior described in this issue seems to have been fixed incidentally so i'm going to close it. granis' comment above still applies so i'll bring it out to another unrelated issue as it seems like a valuable UX improvement
