### ISSUE TITLE
Wallbugging in narrow corners

### ISSUE THREAD

**Issue by Mac-tf2** [momentum-mod/game#1581]
### Describe the bug

Holding a directional key into a very narrow corner causes the player to either fall slowly, or completely stop depending on the angle.

### How To Reproduce

Download this [test map](https://cdn.discordapp.com/attachments/235125108656701440/911043173072117810/test_wallbug.bsp) for multiple different test angles. Hold a directional key into a corner while falling.

### Expected Behavior

The player should fall smoothly at the regular rate.

### Operating System

Windows 10

### Renderer

DX11

**Comment by Gocnak** [comment]
How does 0.8.7 and TF2 compare?

**Comment by hexaflexahexagon** [comment]
Besides the regular wallbugs (which these are definitely not, they behave very differently) tf2 is completely smooth. 
0.8.7 acts the same as steam build.

my bet is on our rampbug fix is going awry because the behavior seems super unnatural and artificial (e.g, you can explosive jump straight up and then start holding w in the corner. you'll slow down, _go up a little (??)_, then slowly fall down). also worth noting that this happens in every gamemode that I tested in (unknown, surf, sj, conc)

**Comment by Gocnak** [comment]
Does booting in `-mapping` and turning off `sv_ramp_fix` make it more like TF2?

**Comment by hexaflexahexagon** [comment]
yup. `sv_ramp_fix 0` = no issues, `sv_ramp_fix 1` = issues start

**Comment by Gocnak** [comment]
Does this still happen with the latest movement + wallbug fixes?

**Comment by hexaflexahexagon** [comment]
seems to be resolved
