### ISSUE TITLE
Portals don't render correctly if "Shader Detail" is below "High"

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1601]
### Describe the bug

World Portals do not render how they should when below "High" of the "Shader Detail" setting in Video Settings. They don't render at a distance and instead only render close up.

This issue is on both DX11 and DX9 however there is no "Both" option.

### How To Reproduce

1. Stand a reasonable distance away from a portal.
2. Change "Shader Detail" to anything below "High"
3. Observe.

### Expected Behavior

Render at much further distances.

### Operating System

Windows

### Renderer

DX11

**Comment by SlidyBat** [comment]
This is caused by `r_simpleworldmodel_drawbeyonddistance_fullscreen` being set to a different value on lower shader detail.

The cvar causes portals that are beyond a set distance to use "simple" rendering which only draws marked entities (something similar is also done for water reflections). However maps aren't marking the entities that should be drawn in this simple rendering mode, and so nothing gets drawn.

We could consider this a mapper error and force them to have their maps support this cvar, or we could just disable this cvar on Momentum.

**Comment by hexaflexahexagon** [comment]
I think this cvar should definitely just be disabled in momentum. for what the majority of people are going to be using portals for, it doesn't make sense to only render a few select things. I don't even know off the top of my head how to mark things in that way anyways.

**Comment by hexaflexahexagon** [comment]
fixed
