### ISSUE TITLE
Incorrect Alpha Fadeing

### ISSUE THREAD

**Issue by NotEagle** [momentum-mod/game#1673]
### Describe the bug

When trying to make material invisible using proxies and $alpha, material instead of turning invisible inverts color to negative.
Happens on dx11 only
![bug screenshot](https://user-images.githubusercontent.com/83903929/152364795-019d01a9-683b-4c4f-80e2-b00b42b796f0.png)
[Testmap.zip](https://github.com/momentum-mod/game/files/7995471/Testmap.zip)
.

### How To Reproduce

Open mat_alphafade_test
Walk away from in map placed objects to see them fade.

How to make custom material
have vtf that has alpha channel
in vmt have proxy that modulates $alpha

### Expected Behavior

when viewing material from far,or when $alpha is 0, it should be invisible.

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by SlidyBat** [comment]
This happens because your proxy is generating an alpha value below 0.
CS:GO isn't HDR, so the alpha value automatically gets clamped to the 0-1 range there.
However in DX11, we do use HDR, so the color/alpha values don't get automatically clamped.

I'm not really sure if this is something we want to fix, would have to speak to other members of the team / mappers to get their input on this.
If you do want to match CS:GO though, you can fix this yourself by adding a clamp proxy to make sure the alpha value is in the 0-1 range.

**Comment by SlidyBat** [comment]
After discussing with others, we've decided we won't be changing this behaviour. As I mentioned before, you can get this working how you want by using the clamp proxy.
