### ISSUE TITLE
Sliding by trigger doesn't provide the same speed possible as before

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1705]
### Describe the bug

Sliding on slopes that can usually be landed on no longer provides the same speed possible.
It's possible this is now more inline with what you'd expect since the speed to me seems more reasonable, however is different and might be a bug so is noted as issue for now.

https://user-images.githubusercontent.com/62808028/155857168-7a90e3de-40d0-4d5e-aab5-6ebbe62f5f7c.mp4

### How To Reproduce

1. Place slide trigger on standable slope.
2. Compare speed from it to previous build.

### Expected Behavior

More speed?

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by jason-e** [comment]
It seems the fix for landing on downhill slopes in the old movement code mistakenly added an extra half tick of gravity when determining the speed adjustment. This algorithm is applied every tick the player is sliding, which resulted in gravity being 50% stronger when sliding down a slide surface. The new movement code does not have this issue and is correct where the old code was not.
