### ISSUE TITLE
engine_no_focus_sleep unrestricted from mapping mode

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1743]
### What feature is your improvement idea related to?

Engine_no_focus_sleep is -mapping mode only

### Describe the solution you'd like

command changed from mapping mode only and made to only work when the timer isn't active

**Comment by hexaflexahexagon** [comment]
i believe this was intentional because you could pseudo-pause the timer with it, if it's the command I'm thinking of. we may need to look at limiting it somehow before unrestricting it?

**Comment by braem** [comment]
this was restricted specifically because it was slowing the timer yeah

we wont do this. i understand the need for saving cpu when alt-tabbed though. A feature request can be opened for that, specifically where server ticks are not slowed

**Comment by braem** [comment]
my b, it working with timer off is good idea :)

**Comment by hexaflexahexagon** [comment]
currently this command seems to be completely unrestricted, even without mapping mode and while the timer is running. e.g.:
```
1. Set `engine_no_focus_sleep` to something very high like `1000`
2. Start the timer
3. Tab out
4. Notice how slow your timer goes down in real time
```
Ideally this should allow for any value while the timer is not running (e.g. in spec) OR when in `-mapping` mode, but once you are playing and the timer is running it should cap at `50` or something, the current default. 

Probably also worth updating the description that console spits out when typing `engine_no_focus_sleep` once that change is done just to explain to people why the command may not be the value they want since it's fairly unintuitive at first glance.

**Comment by Gocnak** [comment]
Yeah that's fine. We're slowly moving away from FCVAR_MAPPING over time, and detecting things like changing this during a run. We could do exquisite prevention methods but it all just gets in the way in the end, the goal would be to just print out when it changes "changing this may invalidate your run, make sure you know what you're doing!" but even then, this is an engine var and that string is very momentum-specific.

I'm just going to close this for now. It doesn't seem realistic for us to reimplement checks without adding a lot of piping into momentum specific code, and in the end this will be detected.
