### ISSUE TITLE
Potential RJ physics inaccuracies

### ISSUE THREAD

**Issue by Mac-tf2** [momentum-mod/game#1769]
### Describe the bug

Several people have spoken up about RJ feeling different. Compare all rocket jump related code to the TF2 code to make sure it's not just ping placebo. Could be potential rocket/weapon behaviour differences since those haven't been looked at since we got engine code.

### How To Reproduce

none

### Issue Map

none

### Expected Behavior

Match RJ 1:1 TF2

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
something that may potentially be helpful if anyone starts investigating this is that jump_apex j2 is something that multiple people have said felt off, the skip (2nd rocket) specifically. i would assume that most likely the knockback from the first rocket on the wall is off giving weird height/speed/angle/etc but take that with a grain of salt.

timestamped vid below
https://youtu.be/lOfGWsuZmNE?t=37

**Comment by Jake-Coding** [comment]
Another thing is bhopping. Bhopping on a ramp gives horizontal vel in mmod, but not in TF2. This could be intended, but also could be indicative of other movement errors. Reported on jump_the c3 l4 the bhop

**Comment by hexaflexahexagon** [comment]
Do you mean on teles specifically? Because I know for a fact that bhopping on downwards slopes gives you more speed in tf2 since it's necessary for setting times on certain kz-type bonuses. I haven't tested with teles myself since it'd typically be random but I would assume it's the same story

**Comment by jason-e** [comment]
> Another thing is bhopping. Bhopping on a ramp gives horizontal vel in mmod, but not in TF2. This could be intended, but also could be indicative of other movement errors. Reported on jump_the c3 l4 the bhop

To clarify this if I understand right, it's not that you don't gain speed on slopes in TF2 (you do), but that sometimes players use setups to get a bounce, and if that happens to also be on a slope, then our downhill slope fix activates and gives you the speed you would have gotten from a normal collision.

If this is correct, and gaining speed from horizontal slopes is not always critical (i.e. randomly not getting speed would never be a problem), then we can just turn off `mom_mv_fix_downhill_slopes` on RJ/SJ. If there are places where slopes *are* used for speed, then we might need to add special behavior to the fix to make it only activate in certain conditions.

**Comment by hexaflexahexagon** [comment]
We have been seeing another issue for quite some time that never got tracked officially which is probably very similar to this. Rockets shot at a steep angle (looking more directly downwards) now sometimes fizzle when hitting a surface they would otherwise be fine on in tf2. To illustrate:

This angle explodes normally:
![image](https://user-images.githubusercontent.com/62961532/164566873-d246b074-c835-4651-b68d-79bd5a738f97.png)

This angle fizzles:
![image](https://user-images.githubusercontent.com/62961532/164566886-094044bb-707c-4e82-af3c-20ad43ea30f7.png)

Screenshot of the map in hammer (top trigger is func_nogrenades):
![image](https://user-images.githubusercontent.com/62961532/164567113-3d96ddc9-8bdc-4a18-87ce-79cf50cbb6be.png)

In tf2 you only need a gap of 1 unit between a surface and a func_nogrenade for a rocket to still be able to explode on it 100% of the time, while this is a gap of 16 units where a large number of rockets hit the nogrenade above the surface. 

edit: for reference, the tf2 rocket is ~37 units long and ~7 units tall. see picture provided by Gentle Puppet: 
![image](https://user-images.githubusercontent.com/62961532/164588686-6d82e7e4-e0bb-43e2-b8b7-1523e00b253c.png)


Map download (go to the course in the water spawn room labeled "pogo"): http://cdn.jumpacademy.tf/?map=jump_academy_classic_b

**Comment by hexaflexahexagon** [comment]
The two issues raised in comments have been split into their own cards, https://github.com/momentum-mod/game/issues/1892 and https://github.com/momentum-mod/game/issues/1893. The subject of the main card I think is mostly resolved, any further issues can be raised as more specific and reproduceable cases in new cards later down the line
