### ISSUE TITLE
Ramps acting more surf-like in low AA modes

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1879]
### Describe the bug

Gaining height by strafing up ramps in low AA modes is far more efficient than is intended

### How To Reproduce

1. open rj/sj/ahop map with surf
2. start sliding on a ramp
3. strafe up the ramp
4. observe how much more effectively you can climb them than before the update

### Issue Map

rj_home or any map with a ramp

### Expected Behavior

Typically you get what seems like no height from trying to strafe up a ramp in RJ/SJ and a little bit in ahop

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by chrb22** [comment]
I assume this is because of a fix related to your air accel getting quartered when you have a low positive vertical velocity. It isn't listed in the changelog, but I can't think of anything else. The fix seems to totally remove the air accel quartering, but that shouldn't happen in low airaccel modes.

To my understanding, the quartering is there to prevent you from scaling steep inclines, but the implementation overlooked that it is also possible to trigger the change when you aren't touching something.
From `CMomentumGameMovement::CategorizePosition`:
```cpp
// Try and move down.
TryTouchGround(bumpOrigin, point, GetPlayerMins(), GetPlayerMaxs(), MASK_PLAYERSOLID,
               COLLISION_GROUP_PLAYER_MOVEMENT, pm);

// Was on ground, but now suddenly am not.  If we hit a steep plane, we are not on ground
if (!pm.m_pEnt || pm.plane.normal[2] < 0.7f)
{
    // Test four sub-boxes, to see if any of them would have found shallower slope we could actually stand on
    TryTouchGroundInQuadrants(bumpOrigin, point, MASK_PLAYERSOLID, COLLISION_GROUP_PLAYER_MOVEMENT, pm);

    if (!pm.m_pEnt || pm.plane.normal[2] < 0.7f)
    {
        SetGroundEntity(nullptr);

        // probably want to add a check for a +z velocity too!
        if ((mv->m_vecVelocity.z > 0.0f) && (player->GetMoveType() != MOVETYPE_NOCLIP))
        {
            player->m_surfaceFriction = 0.25f;
        }
    }
}
```
They basically didn't consider the first `!pm.m_pEnt` touching check and just assumed it was only the `pm.plane.normal[2] < 0.7f` steepness checks that led the code arrive at `player->m_surfaceFriction = 0.25f`. A quick fix to that would be to add `&& pm.fraction != 1.0` to the `if` right above it, such that your air acceleration can only get lowered if you are up against something steep. Can't use `pm.m_pEnt` as `TryTouchGroundInQuadrants` overrides that.

**Comment by Shegetz** [comment]
setting `mom_mv_disable_surface_friction` to 0 corrects this behavior

**Comment by chrb22** [comment]
Oh, so I'm guessing that ConVar just overrides any change to `player->m_surfaceFriction` and isn't specifically targeting the quartering?

**Comment by jason-e** [comment]
Correct. I've fixed the problem by only overriding when `player->m_surfaceFriction` is filled in from the surface properties -- should be in the game on the next build.
