### ISSUE TITLE
Teleporting using a "trigger_teleport" out of a trigger calls "OnStartTouch"

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1891]
### Describe the bug

If you are in any trigger which has access to a "trigger_teleport" without having left the trigger, teleporting out of that trigger calls "OnStartTouch", and triggers "OnEndTouch" twice, implying you're somehow leaving the trigger for a single tick before actually being teleported by the "trigger_teleport".

### How To Reproduce

Download this map for testing, entering the trigger will make a sound, using the teleport should not cause that same trigger to make the sound again.

[test_starttouch.zip](https://github.com/momentum-mod/game/files/9603803/test_starttouch.zip)

### Issue Map

N/A

### Expected Behavior

Don't trigger "OnStartTouch" while inside a trigger when being teleported by "trigger_teleport", and only trigger "OnEndTouch" once.

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by jason-e** [comment]
Ah I had a feeling something like this would happen. This is caused by Momentum's teleport logic [here](https://github.com/momentum-mod/game/blob/b0a25ddb2d809de70313a2bc0e75570c7e47fb3a/mp/src/game/server/momentum/mom_player.cpp#L935) which I was worried about as it's not really proper to mess with trigger events this way. That was done to handle teleporting between zones better, but I know a better way to handle that so it shouldn't be too bad to fix. Thanks for the nice reproduction map!

**Comment by Gocnak** [comment]
Was this fixed recently in 0.10.0's branch? Adding it to the board but feel free to close if so.
