### ISSUE TITLE
"World Lights..." setting still in Mom. settings panel

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#195]
Submitted by Team member

**Comment by Gocnak** [comment]
The setting is still there even though we default it to off, mostly because we aren't sure if we want to keep it quite yet. It wasn't removed so there's no bug here, and removing it (https://github.com/momentum-mod/game/commit/e737dd95c5ab2d9152b05a716ff7932f3ec0d109) would be an enhancement, if any at all. Closing for now, we'll decide later what we want to do here.
