### ISSUE TITLE
If mouse is disabled and you look at lobby or scoreboard and you use the right click to enable the mouse you gain all functionality of both windows

### ISSUE THREAD

**Issue by SlidyBat** [momentum-mod/game#197]
Maybe just make it so mouse always has control of both windows while in spectator, if possible? To avoid any confusion

Issue reported by Garanimal

**Comment by Beetle179** [comment]
Garanimal: “In spectate mode the mouse needs to be disabled before opening the lobby menu, otherwise you lose all right click functionality"



Note from Beetle: this was that issue I had on stream with the lobby-menu-while-spectating thing.
Not necessarily a bug, but not entirely clear how it works.
https://www.twitch.tv/videos/421674709
