### ISSUE TITLE
Investigate why KSF surfers feel that Momentum Mod is easier than CSS

### ISSUE THREAD

**Issue by granis48** [momentum-mod/game#1993]
### Describe the bug

Time and time again we hear css surfers say that Momentum Mod is easier than CSS. At first this could be shrugged off as placebo or the fact that the game eliminates server latency, but the consistent rate of people complaining about this makes me think there has to be some underlying difference between surfing on a CSS server and in Momentum Mod.  
  
Because of the uncertain nature of this issue I have not found any consistent timeframe when people started noticing this, although I personally started taking notice of this after the move to Chaos engine. I have asked and talked to multiple (both pro and decent) surfers from KSF and they all just say "It just feels easier, hard to tell why" or that "It just feels like the tickrate is higher or something".  
  
  
Possible reasons for this discrepancy: 
- Simply the fact there is no lag from server latency.  
- ~~The bug where your FPS affects the speed of the local server(?). This is something that has been [noticed in csgo](https://youtu.be/5GneP6MuVOk?t=363). (possibly related to [this issue with running the map for long times](https://github.com/momentum-mod/game/issues/107)).~~ (this was apparently fixed a while ago)  
  
Other things that can have been proven not to be the cause of the issue since players still experience the game feeling easier with these settings turned off:  
- "null binds" (or "Allow opposing movement keys") are on by default in Momentum Mod, which is not a supported  thing in css.  
- The improved Raw Input setting called "On (tick-aligned)" which polls your mouse movement better than css does. This gives a noticeable speed gain for worst case scenario players (little to no gain for the average player).  

### How To Reproduce

.

### Issue Map

This seems to be an issue on every map but more noticeable on the really hard "unit" maps where the main difficulty is maintaining optimal speed gain throughout the map. 

### Expected Behavior

If there is a legitimate difference between surfing in Momentum Mod and in CSS, then we would want to pinpoint what that difference is. Otherwise we run the risk of getting bad criticism when "Your momentum record isnt even the real record because it's easier, momentum = cheating" becomes a valid argument.  
  
Surf in Momentum Mod should be proven to be identical to css (without server latency) or at the very least have a known difference in gameplay that we can pinpoint the cause of. 

### Operating System

win10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
A verifiable way to prove it would be to effectively create a movement recorder and play back the exact same inputs on both. If the player ends up at the same spot in both cases then it instantly disproves it.

**Comment by ResistanceIF** [comment]
https://www.teamfortress.tv/5590/repost-see-player-keypresses-when-watching-a-dem There's apparently a way to extract inputs from a demo in TF2, does this same process work in CSS?

**Comment by Arkanoid0** [comment]
id bet that would work in css, i don't think the demo format changed at all in source1 games, but i could be wrong there. A bigger problem is that just because one set of the same inputs produces the same outputs it doesn't prove that its actually the same, firstly because game feel is very important, a TAS playing the same inputs with 1 frame of visual lag vs 1 second of visual lag will preform the exact same, but its clearly not a 1:1 experience.

Secondly, its not enough to say "this subset of possible actions is the same", you need to be able to prove that all possible subsets of actions produce identical results. For surf, i think we should be able to unit test in a comprehensive enough way to prove that its not mechanically easier(or find previously unknown discrepancies) that is convincing to people, but we should figure out and be able to explain exactly why momentum has an improved feeling, or people won't trust our results.

**Comment by jason-e** [comment]
> * The bug where your FPS affects the speed of the local server(?). This is something that has been [noticed in csgo](https://youtu.be/5GneP6MuVOk?t=363).

This was fixed in Momentum back in June 2022. I think that bug would be more likely to make the game harder as it just makes the game run faster without actually changing the physics.

Null binds would definitely be a good thing to have people test with/without, it's possible that's all this is.

> game feel is very important, a TAS playing the same inputs with 1 frame of visual lag vs 1 second of visual lag will preform the exact same

Very true, but if we can verify that the game physics themselves are working as expected, then this whole thing becomes a selling point instead of a problem (Momentum is easier just because there's less input lag or something like that)

I think playing back pre-recorded inputs on both games and comparing the exact movement that results is the way to go. Ideally we would do this on an actual KSF server in case there's actually something weird going on with one of their plugins, but that would require some collaboration with them.

I think I can handle all of the testing required (on a custom non-KSF server at least) though I do not have an external movement recorder so I would just record inputs via SourceMod, which would _probably_ be an adequate way to do it.

**Comment by granis48** [comment]
I'm sure that with a traditional movement recorder we can verify this quite easily, one made with sourcemod would most likely not be possible to test on ksf servers. I have a good relationship with the admins there and could do this without any problems, they're just really protective of their server and plugins so we will not be allowed to do anything that requires disabling VAC or adding/modifying plugins

**Comment by jason-e** [comment]
I made a simple SourceMod plugin that records inputs received by the server and the resulting input, recorded a quick run of surf_ace on CSS, and played back the inputs on Momentum Mod:

https://user-images.githubusercontent.com/2745352/220519795-e1af86b7-6cc7-4bb2-a99e-7674565bee36.mp4

For this test I just had to disable `mom_mv_normalize_jump_height` since that changes jump height in Momentum compared to what you would see in CSS. As you can see, there appears to be effectively no difference in basic surf movement in Momentum compared to CSS. The fact that there is any difference at all is probably because we use different implementations of trigonometric functions (sin/cos).

Based on this, I think it's safe to say that the physics of Momentum surf are not flawed in some way that results in easier movement. It's possible there is still some component that does make Momentum "easier", but it's not the physics doing it. There could be some benefit to our local networking or some other difference that provides better immediacy to game input and feedback, and if that's the case, that's certainly a benefit rather than a flaw.

**Comment by Gocnak** [comment]
Excellent work, Rio.

Going to be closing this issue, however it can act as a point of reference for any doubt in the future. Hopefully this helps convince some doubters, though I understand it may not, and there's not much we can do past that.
