### ISSUE TITLE
Improve synchronizer functionality

### ISSUE THREAD

**Issue by 5xp** [momentum-mod/game#2044]
### What feature is your improvement idea related to?

Currently, Synchronizer doesn't distinguish between groundstrafe and airstrafe. This means it isn't very useful for attaining high prespeeds.

I assume this is because internally the optimal yaw delta is calculated as $\large\arctan\left(\frac{30}{v}\right)$, which is true only in the air with high sv_airaccelerate.

### Describe the solution you'd like

Optimal yaw delta can be found by

$$
\Large{\arctan\left(\frac{a\sqrt{v_\text{fric}^{2}-\left(s-a\right)^{2}}}{v_\text{fric}^{2}+a\left(s-a\right)}\right)}
$$

where $\large s$ is the speed-cap ($260$ on the ground, $30$ in the air), $\large v_\text{fric}$ is velocity after friction is applied, $A$ is the acceleration constant ($5$ on the ground, $1000$ in the air), $\large T$ is the tick interval, $\large a$ is max acceleration ($\large \min(s,  As_\text{run}T$).

Notice that when substituting default bhop values, the expression simplifies to $\large\arctan\left(\frac{30}{v}\right)$. But on the ground, we have to consider a large $\large s$, small $\large a$, and velocity with friction, which can be found by

$$
\Large{v_\text{fric} = \begin{cases}
v(1-cT)\text{, } &\ v \geq d \\
v-cdT\text{, } &\ v < d
\end{cases}}
$$

where $\large c$ is the friction constant, and $\large d$ is the stop speed.

When it comes to Synchronizer, particularly for groundstrafing, I believe the most useful value is the optimal yaw delta at the maximum ground speed, which can be found by

$$
\Large{v_{\text{max}}=s\sqrt{\frac{A\left(2-AT\right)}{c\left(2-cT\right)}}}
$$

When using default bhop values, this gives us a maximum ground speed of $289.94633564$. After applying friction, the optimal yaw delta at this speed is $1.0176549946$.

Heres a video of how this might look:

https://user-images.githubusercontent.com/62446202/233551209-050ac78f-cc05-4468-8145-568c8168a528.mp4

This would obviously be best implemented in C++, but here is how I've implemented it using Panorama.
https://gist.github.com/5xp/8f9fa306f18c043f0d6eaaba88f09dd5

**Comment by tsa96** [comment]
Wow, this is really great stuff. Without a Git diff it's a little hard to tell what stuff is changed from the gist you posted, but ground speed calculation looks good - though since it's constant until you change a cvar we should definitely avoid doing that calculation each frame. That being said, @PeenScreeker wrote the current Syncronizer stuff so knows it best, be good to get his input.

Would you be up for PRing this into the [panorama repo](https://github.com/momentum-mod/panorama)? That way we can give it a full review with code comments.

And in terms of moving stuff to C++, it prooobably should be, though then it unfortunately has to be closed source. With our more expensive Panorama panels, we need to benchmark everything properly first and see if we can get the JS stuff faster. Javascript's `Math` library operations can actually be remarkable fast in V8, and keeping stuff like this open is a really big plus for us, so we may well stick with JS.

**Comment by TEKN1SHUN** [comment]
@tsa96 I definitely agree with moving some of the calculations to c++. I think that will make sense for CGAZ/defrag HUD also. My hope is that we can do the complex/expensive stuff once in engine, and the HUD can reference those values instead of recalculating similar values everywhere they're needed. Let's get together when you have some free time to chat about performance and benchmarking.

@5xp very nice work! Really looking forward to improving the player performance feedback tools. Thanks for opening this issue. +1, definitely open a PR if you're up to it.
