### ISSUE TITLE
Add input for setting mouse sensitivity in distance per 360

### ISSUE THREAD

**Issue by ImplyDoods** [momentum-mod/game#2047]
### Is your feature request related to a problem?

so like everyone knows there sensitivity in CM per 360 since all the converter websites use that so it'd be cool if you could input it in cm per 360

### Describe the solution you'd like

there could be an option to add your dpi and cm per 360 instead of the regular source engine values

### Describe alternatives you've considered, if any.

all so it'd maybe be cool if you could all so input sensitivity values from other game engines maybe have this under a drop down menu idk

**Comment by tsa96** [comment]
I think this is a really cool idea, and should be easy to do. We'd need a `TextEntry` for DPI, another for Desired CM Per 360 (maybe an extra dropdown for different units, kinda overkill though, just centimeters is an SI unit after all). Then a button that on press, does the calculation and updates the sensitivity slider itself (that's better then using `GameInterfaceAPI.ConsoleCommand`, which we intend to remove in the future). Or we could even make it so the second TextEntry is just "CM per 360" and changing your sensitivity value updates the value in there, if you have a DPI enter in.

Doing sensitivities from other games is overkill IMO though, too much extra UI needed.

**Comment by jason-e** [comment]
I'm not sure how this would work since translating in-game movement to physical movement requires knowledge of mouse DPI which the game has no way of knowing. Even if we had something where you could input that value manually so it could do the calculation, I've heard 1 DPI for one mouse is not necessarily the same as 1 DPI for another mouse. If anything, we could have some built-in tool that helps you figure all that out by having you move your mouse a certain distance (which you would have to measure out) and from there it could tell you everything you need to know about your sensitivity and DPI.

**Comment by tsa96** [comment]
Other sites and tools like https://www.mouse-sensitivity.com just use DPI, I think we can be confident enough in that even if it's not totally accurate. And yeah, we'd just let players input the DPI itself.

This was first suggested as Diabotical has the exact same thing (though that's the only other game I'm aware of) and would be extremely easy for us to do in just Panorama Javascript
