### ISSUE TITLE
mom_map_download_queue_parallel should not allow more than 3 concurrent downloads

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#206]
"`mom_map_download_queue_parallel` doesnt seem to work properly. 
still wont let me download more than 3 maps concurrently”

Submitted by milo

**Comment by braem** [comment]
To clarify the problem, >3 maps can be download at the same time. For instance, if `mom_map_download_queue_parallel` is 4, 4 maps can be downloaded and the 5th will be held in a queue (will not have a progress bar & shows as green on the map dialog).

The problem is that when we are downloading >3 maps at the same time, the 4th, 5th, etc. will have progress bars (are in the downloading state) but they won't actually begin downloading:
![image](https://user-images.githubusercontent.com/9014762/79676584-5b9b3100-819c-11ea-98ee-0ecfd5db46ce.png)
Might be that it is downloading very slowly, or there is some cap on the amount of `HTTPRequestAndStreamResponse`'s.

**Comment by Gocnak** [comment]
Ah, good research. Maybe then we should just cap the parallel to 3. Seems fine given that people mass downloading maps would be otherwise taking a ton of bandwidth from our site. I'll rename this issue then, should be a one-line fix.
