### ISSUE TITLE
Question about PBR shader documentation

### ISSUE THREAD

**Issue by BenLubar** [momentum-mod/game#2088]
The documentation on VDC: <https://developer.valvesoftware.com/wiki/PBR_(Strata_shader)>

It seems to mention a lot of shader parameters that aren't defined at all in https://github.com/momentum-mod/game/blob/develop/mp/src/materialsystem/stdshaders/pbr_dx9.cpp

For example, `$envmapparallax`, `$bdrf_integration`, and `$bumbframe2` (even if I assume the spelling is a typo).

Are these defined somewhere I'm not looking, or is the VDC article incorrect (either due to these parameters not existing or due to them being game-specific)?

**Comment by Gocnak** [comment]
Hello, the linked shader code is from our last open source release, 0.8.7. The VDC documentation is for our latest version of the shader found in our closed source Strata engine build.

We'd look into open sourcing it again but unfortunately it would require the DX11 (shader model 5.0) changes to also be public, which touches too much engine code currently to cleanly separate.

We also haven't really been keen on documenting things quite yet since we're in active development and regularly updating things like shaders, but when we do we will either use VDC or the Strata wiki for shared/base engine documentation, and the momentum mod docs site for our stuff.

**Comment by BenLubar** [comment]
Ah, thanks!

**Comment by BenLubar** [comment]
An update for anyone hoping for this: with the permission of the Strata Source team, I've been able to backport the current version of the shader to shader model 2.0b and 3.0. The parallax occlusion and some of the parameters that have a 2 in them are removed from 2.0b to save on instructions (and because it doesn't like loops) and the parallax corrected cubemaps have a slightly different input format due to what Alien Swarm: Reactive Drop uses, but apart from `$emissionfresnel` which is new, everything should match.

https://github.com/ReactiveDrop/reactivedrop_public_src/commit/6fded2eb012b5f832e8cb5226c2e781d387cec08
