### ISSUE TITLE
Meta Game Mode

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#2123]
Refactor system_gamemode to track two gamemode states, a *meta* and an *active*.

The *meta* mode is the state UI lives in, both a getter and an event is provided in GameEventManager and Panorama for whenever this changes.
New map selector will always be in a single gamemode, based of off this value.
The meta mode can be changed by UI, and by command. For 0.10.0, just the map selector radio buttons will do this. In the future, a dedicated "gamemode hub" page will handle it.

The active mode is just the state the game is currently in. Whenever a map is loaded, the active mode is set to the meta mode. There is no other way that the active mode can be changed, and it's changing does not provide any events to Panorama - Panorama should just listen to level change and just use a getter.

`mom_gamemode_override` will be removed.

State should be persisted, probably using a hidden convar, and a command for setting it, so we get autocomplete.

This is just a rough draft, we'll discuss more on Saturday

**Comment by jason-e** [comment]
`mom_set_gamemode <gamemode>` (console command)
- Used by gamemode selection UI
- Supports autocomplete when entering manually
- Fires some event like `MetaGamemodeChanged`
- Sets some archived hidden ConVar like "mom_saved_gamemode", remembering this gamemode for when the game client starts again

`GetMetaGamemode()`
- Gets the gamemode the overall UI is in (map selector, hub, etc, anything that is shown when not in a map or when the menu is opened while in a map)
- Can be `none`, in which case the UI will back out of any mode-specific screen until the a mode is selected

`GetMapGamemode()`
- Has no on-change event of its own (UI elements should listen for map load events instead)
- Dictates what "in game" UI should be showing (leaderboard, track list, maybe determine which HUD elements should be shown?)
- Not changable directly -- always equal to whatever the "meta" gamemode was when the map loaded
- Can be *any* game mode, regardless of what modes are ranked/official for the current map. Loading any map on any game mode is as simple as using `mom_set_gamemode` (if not already on the desired gamemode) followed by `map` at any time. Maps would not dictate the current mode on load by default, hence an "override" is not needed.

One thing that will be slightly less convenient with this design is using the console to quickly load a map from a different gamemode when the user does not actually intend on playing it on an unofficial/unranked mode. This is important because most maps will only have one official/ranked mode, which is usually what the user intends to play. Perhaps we could have another command similar to `map` (call it `go`?) which will first check if the current meta gamemode is official/ranked on the specified map and change it if it is not, before loading the map. Alternatively, we could flip this around and make `map` have that behavior, and have some other command which does not check the gamemode first. The `go` idea is nice because it leaves `map` unmodified and feeling like a low-level command, though perhaps making `map` itself the go-to command for most use cases will feel more familiar.

**Comment by tsa96** [comment]
Cheers for this, need to discuss the `go`/`map` command more but everything else above is just a better version of what I wrote

**Comment by tsa96** [comment]
According to Oxzy we should be able to do autocomplete on convars fine, there's some autocomplete callback we can override when declaring it.

**Comment by Panzerhandschuh** [comment]
@jason-e The archived convar `mom_saved_gamemode` is not necessary because Panorama already saves the map selector's filter state to persistent storage.

**Comment by tsa96** [comment]
Convars support autocompletion, I don't see any reason to use a command not a convar here, if anything it's far more confusing. 
@jason-e are there are any other actual reasons for the convar being hidden?


Then r.e. `map` vs `go` command, when we last discussed (I think was last team meeting) we seemed in agreement that adding a second argument to the `map` command is better. It doesn't affect existing behavior of the `map` command (since it only have one argument currently), what would be the problem?

**Comment by tsa96** [comment]
`mom_gamemode` would be best as a command IMO

**Comment by tsa96** [comment]
From rio
```
map <mapname> =>
    if the map is official =>
        if the meta mode is ranked for that map => go ahead and load on meta mode
        if the meta mode not ranked for that map => *switch* meta mode to the first ranked mode, then load on that
    if the map is unofficial =>
        try and detect the mode from the map prefix and switch the meta mode if successful. then load on meta mode (even if prefix detection failed to change it)
        
map <mapname> <gamemode> => switch the meta mode to the specified gamemode, then load the map on that mode even if unranked
```

**Comment by Panzerhandschuh** [comment]
Meta game mode is implemented, but `mom_gamemode_override` is still being used. We can remove it after adding the gamemode parameter to the `map` command.
