### ISSUE TITLE
Fix landmarked trigger_teleports

### ISSUE THREAD

**Issue by Panzerhandschuh** [momentum-mod/game#2202]
There's some small regression with the refactored trigger_teleport

**Comment by jason-e** [comment]
So I think this is actually an expected behavior and not a bug. It's something we need to use Lumper to fix on affected maps.

Part of the refactored/cleaned up logic was uniting CS:S/TF2 landmark teleport logic with CS:GO's logic. CS:S and TF2 apply only an origin offset for landmark teleports while CS:GO transforms both origin *and* angles respective to the landmark and destination origin and angles.

The CS:GO behavior is a superset of the old behavior. In cases where the landmark and destination have the same angles, both games have the same behavior, but CS:GO has expanded capabilities by being able to do relative angle transformations if desired.

Some maps originally made for CS:S/TF2 have angles set on the landmark and/or destination entity, and this results in different behavior when angle transformations *are* supported. In these cases, we just need to update the `angles` key for the landmark and/or destination entity so they are equal to each other (probably equal to `0 0 0`). The associated trigger_teleport may also need `UseLandmarkAngles` explicitly set to 0 if `spawnflag` `0x20` is not set.

Before the trigger_teleport cleanup, it had a key which specified whether the CS:S/TF2 behavior or the CS:GO behavior should be used, but since this had to be set manually anyway, it was removed in favor of a cleaner entity design and the manual fixing of `angles`.
