### ISSUE TITLE
Allow creating temporary (per-run) start marks in stage zones

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#221]
"Can someone add that when mom_start_mark_create is used mom_reset will not set you there (mom_restart does). Im not sure if this is intended or not."

Submitted by Garanimal

**Comment by Gocnak** [comment]
This is a bit iffy. We're not going to allow setting a start mark for stages in the middle of your run, as it's akin to using a saveloc in the middle of your run. But, stages should be allowed to set them if people are going for ILs. I'm gonna move this off 0.8.1 for now because ILs are coming in 0.9.0.
