### ISSUE TITLE
You can skip the start time and cause an exception at the finish on rj_home

### ISSUE THREAD

**Issue by Shirge** [momentum-mod/game#2211]
### Describe the bug

![Screenshot (78)](https://github.com/user-attachments/assets/efb7db4b-e03c-4671-aa18-89e32193c8a6)
You can jump over the starting green box and cause an exception when you reach the end

### How To Reproduce

1. Jump over the starting box
2. Finish the map

### Issue Map

rj_home

### Expected Behavior

Not being able to jump over the start

### Operating System

Windows

**Comment by tsa96** [comment]
Thanks for the report but we don't track issues with map zones on Github. After 0.10.0 they should be reported via the dashboard site, and until 0.10.0 we don't care about them, since they're all getting remade from scratch. 

I'm not sure we have this exact JS exception tracked, but refactors to new TS timer code are likely to make this irrelevant, and pre 0.10.0 zones can't be used for testing post 0.10.0 zones.
