### ISSUE TITLE
Paint behaves strangely in lobbies

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#229]
Sometimes, paint will flicker colors (after already being applied). Your paint will not take on the correct color.

https://clips.twitch.tv/PuzzledCreativePotPunchTrees

Submitted by Beetle179

**Comment by Gocnak** [comment]
Does this still happen on Chaos?

**Comment by Gocnak** [comment]
Going to close as this is something that needs to be retested, the original underlying issue with colors being weird has been fixed.

Paint in general needs an improvement to not rely purely on the material so that paint can be properly networked and displayed with the right color and decal size. That itself is another card, but the original strange behavior of this card should be fixed in Chaos.
