### ISSUE TITLE
OSX: map selector color inconsistencies

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#294]
(not sure if it only happens on osx)

1. right click map haven't downloaded > add to library (map red) > download map (map green) > restart game > map turns red again (not intentional) > map will appear as not downloaded > right click to "download" map again > map turns white but doesn't download because it's already installed > stays white regardless of what I do afterwards

2. remove a (downloaded) "green" map from library (map turns white) > readd to library > map stays white (not intentional) regardless of what I do afterwards (until it turns red on game restart like above)

I assume removing the maps locally will restart the whole process

**Comment by Gocnak** [comment]
So I tried recreating both and noted this:

1. I can't seem to make it happen anymore, it may have been fixed.

2. This is intentional. Check out the `mom_map_delete_queue` convar. We'll get a better way to convey this in the future with some sort of settings panel for the map selector.

Also a further note, we will not be supporting OSX in the future, so if this is an OSX-specific bug we won't fix it.

I will be closing this for now. If it happens on 0.8.2+ we can look into it.
