### ISSUE TITLE
Game accepts input while color picker is open

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#326]
https://www.youtube.com/watch?v=exWLRN9baM4

Reported by Beetle

**Comment by Fuhsahd** [comment]
Same thing happens with the paint gun as well, you can fire paint whilst its open.

**Comment by SlidyBat** [comment]
Did some investigation, this seems to be caused by the `DoModal()` call when the color picker is displayed: https://github.com/momentum-mod/game/blob/7d9a96ea944a6db11abe79d6aa3ce223a53eb676/mp/src/game/client/momentum/ui/controls/ColorPicker.cpp#L401-L406

We could fix this by removing the modal stuff from color picker, but I'd rather spend more time diving through code to find the root cause since modal dialogs definitely shouldn't be doing this.

**Comment by tsa96** [comment]
This exists in other Source games btw - turnbinds will do the same thing in CS:S if you open the advanced keyboard options dialogue (I'm not actually sure if this is a modal). So presumably it's always been a thing but only shows up when you have configs with turnbinds. So def worth looking through the VGUI code to fix entirely

**Comment by Gocnak** [comment]
Hi, I found the problem. Frame's `DoModal` calls into the `input()->SetAppModalSurface()` function but the game doesn't respect that inside its own input. A solution is to just check to see if the `AppModalSurface` is non-zero and to swallow every keypress that would have normally happened.
