### ISSUE TITLE
Replace ClipRayToEntity with more optimized version

### ISSUE THREAD

**Issue by swoopae** [momentum-mod/game#342]
source's engine tracing functions are incredibly poorly optimized/implemented since they were written a long time ago.

i propose replacing at least some of the functions with better ones (i guess you guys don't have access to source's engine so perhaps you could hook the nasty functions (?))

eg: [clipraytoentity](https://github.com/momentum-mod/game/blob/e3efc48eb58cf56af61b2fef8d0bf7e3bf754680/mp/src/public/engine/IEngineTrace.h#L142) should be hooked and [this](https://www.unknowncheats.me/forum/counterstrike-global-offensive/345397-performance-raytracer.html) should be used instead of calling the original vfunc.

edit: this would also bring a huge fps boost

**Comment by Gocnak** [comment]
Adding the source files (with full credit) here, for future reference in case the original post is deleted:
[Documents.zip](https://github.com/momentum-mod/game/files/5413879/Documents.zip)

**Comment by jason-e** [comment]
I don't think this is something we actually want to use for a few reasons:
- It's actually just an algorithm for tracing a ray against a bounding box. Since it's not for *hull* tracing it couldn't be used for many things, not to mention a ton of collidable objects are not defined by simple bounding boxes. Complete collision detection needs to support hull traces, arbitrary convex solids defined by any number of planes, and arbitrary models of vertices.
- I wouldn't trust that a different algorithm like this would be a clean equivalent to existing code, especially when used alongside other collision code. For example, this algorithm could have floating point errors which are unexpectedly different from those created by other game code, especially since it does its own coordinate-space manipulations.
- It seems incomplete even for what it *does* support; notably it does not handle anything related to `DIST_EPSILON`.
- I wouldn't say that we have any problems with the performance of the original collision code. After all, it was good enough almost 20 years ago for the hardware available at the time, even with multiple players on one server. I suspect a lot of the reported  speedup of that algorithm would come down to its limited scope (rays against bounding boxes only).

**Comment by Gocnak** [comment]
Gonna close this then as not planned, those are great points.
