### ISSUE TITLE
Jumping while exiting start zone reduces speed

### ISSUE THREAD

**Issue by tuxxi** [momentum-mod/game#36]
Bug: If the player is in the air as they leave the start zone, their xy velocity is reduced by an arbitrary amount. The amount that your velocity is reduced by depends on how close you are to the edge of the start zone when starting the jump (so perhaps your z height?). It seems that if you are more than about 16 units away from the boundary you will lose no speed at all. Additionally, if you do not jump while exiting the start zone, your horizontal velocity is not reduced by any amount. 

I should also note that the velocity reduction appears to be independent of the mom_zone_maxsleavepeed value, although is probably a result of a bug in that class.

**Comment by RabsRincon** [comment]
Hi, Tuxxi.
While it's true that we intend to improve how we handle max leaving speed from the start trigger (You can check our to-do [here](https://github.com/momentum-mod/game/blob/master/TODO.md), (*it is code focused, but you can get an idea of what we're doing*) ) (By limiting how much you can bunnyhop on a row inside the start trigger), what you're experiencing is an intended behaviour of the start trigger, to avoid the player leaving with an exaggerated speed.

The amount of speed lost is not arbitrary, but the necessary to get you to a maximum of 260 units per second (as default). We also plan on updating this default value to the maximum pre strafe speed.

As for `mom_zone_maxleavespeed`, it's intended to be used as part of the zone creation process, not as a variable to control the map starting max speed (*because it's a mapper decision*), but to set said maximum leave speed of the start trigger when you're building zones. (`mom_zone_edit 1`) (Zones are used to allow us to implement our custom entities into CS:S maps without needing to use the Hammer Editor)

Anyways, thanks for reporting, and hope you stick around :smile: 
Rubén.

**Comment by tuxxi** [comment]
The bug that I reported was causing me to drop below 260 u/s if I left the start zone at exactly 260 u/s XY velocity, but happened to be in the air at the time. Is this the intended behavior?

**Comment by RabsRincon** [comment]
Ok, so after some debugging, what is happening now seems pretty simple:
**1**) Probably your speedometer is only showing XY speed (as it's the default behaviour) (`mom_speedmeter_hvel 1` changes this and shows XYZ)
**2**) Trigger Start checks for XYZ speed, so jumping gives you more speed than shown (+300usp) if `mom_speedmeter_hvel 0`
**3**) Max leave speed is already changed to the maximum pre strafe speed (~290)

The reason then is pretty clear: You were getting more speed that the allowed because you were jumping, and it didn't show to you because you had `mom_speedmeter_hvel 0`

:)

**Comment by tuxxi** [comment]
This may be the intended behavior currently, but reducing the player's XY velocity is not a good thing. If I prestrafe to 285 u/s and jump, my XYZ is guarenteed to be above 290 as I leave the start zone, so it gets reduced. This results in having less XY velocity than the 285 prestrafe, and possibly even less than 260 u/s. We should change the behavior to check for only XY velocity as this is the behavior on blacky's bhop timer and KSF SurfTimer.

**Comment by RabsRincon** [comment]
Oh! We had some discussion about it, I'll check with people that know more
than me about it, but I had an idea to fix this. I'll implement the other
check method (Only XY) now and will set it to default, but keeping the
other one as an available option

:D

**Comment by RabsRincon** [comment]
If you have more questions/ideas/suggestions, please don't doubt and contact us

:)
