### ISSUE TITLE
Replay recording strategy is wasteful

### ISSUE THREAD

**Issue by SlidyBat** [momentum-mod/game#360]
At the moment, the replay recording strategy is to mostly just keep recording everything up until the map is finished, which then leads to the beginning of the recording being trimmed to 2 seconds before the timer started.

This is extremely wasteful use of memory, a better strategy may be to do the trimming as soon as the timer starts rather than when it finishes or possibly just trimming every frame we're inside the start zone.

**Comment by Arkanoid0** [comment]
I personally like that replays show some pre-timer actions, since some modes have prestrafe or other pre-time strats. Maybe a better trim would be to do an initial trim on timer reset, stopping recording/tick trim on velocity in the start zone hitting zero, and restarting recording again on movement within start zone, and keep the extra trim to -2s on map complete.

That should cover all possible cases of unnecessary recording while keeping pre-time.

**Comment by Panzerhandschuh** [comment]
Outdated
