### ISSUE TITLE
[Sticky/Rocket Jump] Add custom trigger that limits explosives

### ISSUE THREAD

**Issue by Hat-Kid** [momentum-mod/game#562]
**Is your feature request related to a problem? Please describe.**
Currently the stickybomb launcher has a hardcoded limit of 3 max stickies out, but to allow mappers more freedom over how to design their levels, a custom trigger should be added that overrides this limit.

**Describe the solution you'd like**
A custom trigger that (either upon entering or only while inside it) limits the maximum amount of stickybombs that can be in the world at any given time. The current limit should be easily visible either through a hud element that appears whenever the current limit is not 3, having these triggers be visible during runs and/or adding a custom attachment to the stickybomb launcher model that shows the current limit.

**Comment by Gocnak** [comment]
I think it could even be generalized to also limit the maximum number of rockets fired inside of it.

**Comment by hexaflexahexagon** [comment]
To expand on this, there are two separate things that are wanted from this entity:
1. Limit the max amount of possible SJ stickybombs out at any given time within an area (3 by default)
2. Limit the amount of explosives for any gamemode that can be used within a trigger without hitting a reset tele or exiting the trigger (infinite by default)

This trigger will also likely expand to be used more generally for limiting all weapons (SMG, shotgun, sniper, etc) so that modes such as surf can use specific guns to shoot buttons and things like that.

**Comment by heysokam** [comment]
Request:  
Add the option to select whether to teleport the player to a target destination when the limit of shots fired is reached or not.

**Comment by hexaflexahexagon** [comment]
if the trigger fired an output when the player used all available shots that would be easy to implement and allow for more functionality besides just teleporting

**Comment by Arkanoid0** [comment]
> I think it could even be generalized to also limit the maximum number of rockets fired inside of it.

This should be generalized to all of XJ and include concs too.

**Comment by hexaflexahexagon** [comment]
closing in favor of #1833 and #1834
