### ISSUE TITLE
Console syntax highlighting

### ISSUE THREAD

**Issue by Isabwella** [momentum-mod/game#736]
**What feature is your improvement idea related to? Please describe.**
I'm proposing syntax highlighting for specific keywords to visually aid users

**Describe the solution you'd like**
I have a mockup design of what I had in mind, but it can be altered any way you'd like:
Before (default):
![image](https://user-images.githubusercontent.com/3002858/81221678-62011980-8fa0-11ea-9302-ab627792c2e8.png)
After (syntax highlighted):
![image](https://user-images.githubusercontent.com/3002858/81221903-b4423a80-8fa0-11ea-8813-ba4be1a57268.png)

**Describe alternatives you've considered, if any**
We could keep the prediction text white, since it could complicate things
![image](https://user-images.githubusercontent.com/3002858/81221994-d936ad80-8fa0-11ea-8ab6-950d32ed206a.png)
Also errors can possibly be different, but bold red for all of it seems sort of important so I left that alone.

[(Album for full comparison)](https://imgur.com/a/nNQCWVJ)

**Comment by Flipybitz** [comment]
This uses my proposed console design for the new ui overhaul, if necessary I can make a mockup for the current console

**Comment by Gocnak** [comment]
Print statements are so variable that implementing this would either require refactoring every print statement found around code, or implementing a post-processor on top of the console using regular expressions... for everything printed. Despite the console not being open, this would still incur a performance hit that some users may find annoying and unnecessary. Since this is also at such a low level (in a VGUI control), it can't be toggled with a convar. Going to pass on this and try to make important print statements more colorful/visual instead.
