### ISSUE TITLE
Main menu spinning arrow icon only loads on game startup

### ISSUE THREAD

**Issue by Flipybitz** [momentum-mod/game#761]
**Describe the bug**
It appears that the spinning 3d momentum arrow on the main menu (not present when using -console or +developer since those bypass the map bg_00 from loading entirely), is never loaded again after you join any map and quit back to the main menu. Seems a bit silly, but maybe there's a reason for this that I'm just not aware of.

**To Reproduce**
Without -console or +developer, when launching the game you will notice the loading bar you get when you load into any map, then the main menu loads as intended with the spinning arrow logo present. Load into a map, and exit back to the main menu and it will be gone. There's no other way to bring it back as far as I know aside from restarting the game entirely.

**Expected behavior**
Ideally, the spinning arrow would be present every time you quit to the main menu. We could even ditch the loading bar for loading it since it seems redundant.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
This entire issue may become defunct depending on how we decide to change the main menu UI later on in development, so that's worth noting.

**Comment by itVictor** [comment]
Technically this behavior is intended, as seen in all source games that support `map_background`.

bg_00 is technically just a regular map, you can load it by doing `map bg_00` in console, although you obviously won't have a timer or be able to move around. The game has `map_background bg_00` built into the startup process so that's why you see it every time you launch the game. Meanwhile `disconnect` will always disconnect to the actual main menu regardless of what map you're on, which is why you can also do `disconnect` on bg_00 after launching the game and you'll go to the actual main menu.

With regards to this issue, you are asking for the `disconnect` command to always do `map_background bg_00` instead of going to the main menu, which may or may not not cause issues (a developer will have to clarify here).

**Comment by Flipybitz** [comment]
> Technically this behavior is intended, as seen in all source games that support `map_background`.
> 
> bg_00 is technically just a regular map, you can load it by doing `map bg_00` in console, although you obviously won't have a timer or be able to move around. The game has `map_background bg_00` built into the startup process so that's why you see it every time you launch the game. Meanwhile `disconnect` will always disconnect to the actual main menu regardless of what map you're on, which is why you can also do `disconnect` on bg_00 after launching the game and you'll go to the actual main menu.
> 
> With regards to this issue, you are asking for the `disconnect` command to always do `map_background bg_00` instead of going to the main menu, which may or may not not cause issues (a developer will have to clarify here).

Yeah I sorta assumed there was a reason behind it and potentially loading into a map when trying to exit a map would be troublesome, but yeah guess we'll see what goc or another developer says about it

**Comment by Gocnak** [comment]
Yeah repeatedly loading into the background map wouldn't be good, since we'd need to override the disconnect command for that to even work. I'm going to say this isn't a problem, and I believe in the future we're going to go with a model panel for the background of the menu anyways.
