### ISSUE TITLE
Working on sounds

### ISSUE THREAD

**Issue by krsu** [momentum-mod/game#8]
Request some sounds also, I have the game startup sound and the main menu idle ambience pretty much done, but what else do we need?

**Comment by Ravennholm** [comment]
✓ Startup Sound: https://soundcloud.com/officialravenholm/startupsound-momentum/s-xDmP2
✓ Main Menu Idle Music (Ambient): https://soundcloud.com/officialravenholm/main-menu-idle-music/s-rSInG


I can also change these later if it's not exactly what we want.

**Comment by Flipybitz** [comment]
We don't really NEED anything yet, but maybe down the line, a few things we could need would be:
-Alternative sounds when landing on the ground (instead of bone crunch sound)
-A sound that happens when the player resets (?)
-Sound for bunnyhop pads to serve as a 'default' sound (one that will never get annoying)
But typically overall, not a lot needs to be changed, or even should be changed for that matter.

**Comment by Gocnak** [comment]
Relevent: https://developer.valvesoftware.com/wiki/Startup_Music

**Comment by Sewq90** [comment]
I made some ambient menu music, https://soundcloud.com/sewq90/momentum-ambient

**Comment by RabsRincon** [comment]
@Sewq90 The track is removed or private. I can not acces it

**Comment by Sewq90** [comment]
wait, for some reason it was private :>

**Comment by Gocnak** [comment]
We appreciate your work, and while we may not end up using it, we will eventually need the startup music.

Moved to trello: https://trello.com/c/d8mLd8bL/23-menu-music
