### ISSUE TITLE
Hitting escape while in game and in the settings panel freezes the player

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#850]
**Describe the bug**
While in game, opening the settings panel and hitting escape (to close it) actually resumes the game and does *not* close the panel, making the player stuck until they press escape again.

**To Reproduce**

- Go in game
- Open settings panel
- Interact with it?
- Press "escape" instead of manually closing the settings panel
- Notice the game goes back "in game"
- You cannot move
- Pressing escape brings back up the gameui, with the settings panel still open

**Expected behavior**
The settings panel should follow the chat dialog's steps and [prevent/allow gameui escape using the concommands](https://github.com/momentum-mod/game/blob/develop/mp/src/game/client/hud_basechat.cpp#L910).

**Comment by braem** [comment]
Looks like this happens when closed with the combobox menu open. Looks like this is a bug introduced when I stopped escape from being pressed on comboboxes, back when escape toggled between game and settings https://github.com/momentum-mod/game/pull/777

I feel that this will be resolved by reverting that commit.
