### ISSUE TITLE
Create .zon files in the VBSP map compile process

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#877]
**What feature is your improvement idea related to? Please describe.**
This is something that's been planned for awhile but there is no issue for it. 

Currently there is no way to get .zon files from maps compiled with zoning entities (eg. [`trigger_momentum_timer_start`](https://docs.momentum-mod.org/entity/trigger_momentum_timer_start/)).

**Describe the solution you'd like**
Edit VBSP to spit out a .zon file when compiling maps with zoning entities through hammer.

**Additional context**
Needed as there should be a way of editing zones compiled in the map without recompiling it. Also I believe they are needed for website integration (downloading newest zones).

**Comment by Gocnak** [comment]
Copying additional context from my duped issue (whoops)

**Additional context**
A nice thing about our implementation of Hammerpatch in Momentum Hammer means that every brush entity has its vertices already stored in the entity lump of the VMF, inside its own "points" chunk. Our VBSP can easily search for this lump for each of these ents and do this exporting, otherwise rejecting standard VMFs if not detected.
