### ISSUE TITLE
Jumping 'stamina' not present in Momentum

### ISSUE THREAD

**Issue by lodyb** [momentum-mod/game#90]
In CS:S, there is a movement mechanic where your first jump will be something like 296.0f, but when you bhop on the spot, you'll jump lower (back to 268.3281572999747f). Stopping for a second and jumping again yields the boosted jump height which is only a couple of units higher. I also feel like I am jumping higher  in Momentum and getting less friction on landing after a jump.

I have created a map which tests a lot of the movement mechanics and the hull, everything is scaled to work with CS:S:
http://lody.be/i/2016/09/1472979011_cb.bsp

Here are a couple of videos showing the behaviour, comparing CS:S with Momentum:
CS:S: https://youtu.be/05fVJj-8jqg
Momentum: http://youtube.com/watch?v=jpmJvc3Q0eA

Hopefully from the videos you can tell that everything is a lot easier and you jump higher in Momentum.

This might seem really arbitrary but it is what CS:S does, and there are a lot of kz and climb maps which utilise this mechanic, so it feels a lot different when the player is not punished for stopping for a second and doing a proper jump.

**Comment by Nolan-O** [comment]
Part of me wishes that we didn't have to support silly things like this. If we were making a movement game from scratch, this idea would be shot down because it's really just awful, unnecessary, arbitrary complications.

**Comment by Gocnak** [comment]
The idea was to support it for the modes that need it; the KZ game mode has stamina built in.

If game modes require this and aren't KZ, we could easily make game modes into flags, where it could be MOMGM_SURF | MOMGM_STAMINA, so that mappers could use the stamina game movement code. 

But that would be as far as it goes, like Nolan pointed out, it seems like an arbitrary feature of CS:S to support without maps that really require it, which most surfing and bhop maps don't.

**Comment by Nolan-O** [comment]
I just think it would be really convenient, save for the sudden lack of properly designed maps, if there was no stamina. Stamina will put the scroll style into a corner away from other game modes and confuse new players. It also makes it harder to design maps that are good for both game modes due to the smaller overlap between the two, which will also contribute to alienating players in one game mode from the other.

**Comment by tuxxi** [comment]
lody,

a mode with stamina mechanics exactly as they are in css already exists in momentum mod. you aren't seeing the behavior because you are using a map with the bhop prefix which automatically sets the game to the default autobhop settings. if you play om an autobhop server all semblance of stamina mechanics will be gone, which is what we are replicating for the default bhop game mode.

if you wish to play with default CSS settings, ie with stamina enabled, just change your map to use the kz prefix and momentum mod will automatically select the scroll stamina mode for you. In the future there will be a way to select your desired game mode regardless of map name but this is how it works right now.

**Comment by lodyb** [comment]
I am on a fence with this now, as you'll have to play differently depending on the map type being played. When maps used combinations of bhop, kz, surf, what happens then?

Something tells me it would make more sense to keep the skill bar high, if surfers don't notice this kind of movement mechanic then no harm is done. If mappers in the future want to utilise this then it's there and it is also consistent. You won't have to learn n different types of mode movement to be good at the game.

Wouldn't it be better to have a gold standard that cannot be confused between modes, even if we decide it removes stamina all together?

**Comment by tuxxi** [comment]
the stamina mode is entirely for legacy support intended for the scroll bhop community. we intend the "official" game to have no stamina at all since it's meant as a surf and autobhop game. very few maps are actively played that include gameplay for autobhop and kz, and the ones that do have both are played on autobhop settings for the most part in the community so that's what we decided to make the standard.
