### ISSUE TITLE
Tools mode and menu background blur

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#959]
**Describe the bug**
Running the game in tools mode and entering a map will make the game render the viewport blurred, as if the menu was open

**To Reproduce**

1. Run the game with `-tools`
2. Enter any map
3. ???

**Expected behavior**
Running the game in tools mode should not cause viewport blurring, even when the input is being eaten by the tools and not the game

**Screenshots**
![image](https://user-images.githubusercontent.com/35622748/93718885-a1419880-fb44-11ea-8e76-7911e4b8bb8b.png)
Tools mode: Game has fullscreen + input

![image](https://user-images.githubusercontent.com/35622748/93718906-c33b1b00-fb44-11ea-8d39-60b8076f6c03.png)
Tools mode: Tools have fullscreen + input

**Desktop/Branch (please complete the following information):**
 - OS: Windows 10
 - Branch: enhance/weapon-viewmodels (rebased 7 days ago, 13/09/20)

**Additional context**
The game is also running with `-forceallmips -nop4` but I do not beileve these have any impact on this issue

**Comment by ghost** [comment]
I got it to vanish with `building_cubemaps 1` when I was testing Hammer earlier, are you able to try that command in tools mode as a workaround?

**Comment by VortexParadox** [comment]
It works! Though it only happens when leaving the menu via the ESC key for me it seems

**Comment by VortexParadox** [comment]
The issue where GUI elements would disappear by attempting to open the menu is also resolved by opening and closing the menu with the console key

**Comment by Gocnak** [comment]
Does this still happen? Looks like this wasn't closed properly...?

**Comment by granis48** [comment]
Launching the game with -tools (and -legacyui through the bat file, win10) still behaves slightly odd, I was not able to replicate teh blurry screen vortex got but the way it goes now is something like this: 

- launch with -tools
- enter main menu just like launching without -tools
- press F10 to enter tools mode, the momentum icon is showing through the menu but pressing F11 to go fullscreen tools mode seems to fix that
- F10 again to go game mode and enter a map
- when on a map pressing escape to open the menu just hides your hud and menu doesnt show at all
- F10 to go into tools mode works but the "engine viewport" doesnt show the game
- sometimes entering game mode doesn't let you see the game, im guessing youre supposed to see it in the engine viewport but since its not working you have to hit F11 for it to show

Thats all i could find right now, everything I was able to replicate and looking kinda jank. So the original issue is fixed but tools mode still needs some work. 

on latest version as of this comment

**Comment by Gocnak** [comment]
Going to close as the original issue was fixed, and we have some other tools-related issues (and can add more) to fix that jank!
